### ISSUE TITLE
Allow for abstract Vertex/Edge Labels

### ISSUE THREAD

**Issue by johnberzy-bazinga** [bitnine-oss/agensgraph#116]
Hello,

Since the Vertex/Edge tables makes use of table inheritance, it might be useful to introduce the concept of abstract labels. OrientDB currently supports a similar [feature](http://orientdb.com/docs/2.2/Concepts.html#abstract-class).

One possible implementation would be to just add syntactic sugar around a check constraint. e.g.:

`CREATE ABSTRACT VLABEL person` would result in an additional check constraint `CONSTRAINT person_abstract_check CHECK (false) NO INHERIT` 

Thanks you,
John

**Comment by kskim80** [comment]
Hi, 
Thank you for your interests and your suggestion.
To my understanding, the abstract label is a label which does not have any instance, that is vertex or edge. Is it right? It can be implemented as you explained. 
I would like to know in what cases the abstract label can be utilized? If it is useful, we will add the feature.

Thank you.
Kisung Kim.

**Comment by johnberzy-bazinga** [comment]
Hello Kisung,

> To my understanding, the abstract label is a label which does not have any instance, that is vertex or edge. Is it right?

Correct.

> I would like to know in what cases the abstract label can be utilized? 

Mostly for the purpose of modelling label hierarchies with additional precision and precision and safety. Also, the additional info may prove to be useful for codegen processes based on the db schema i.e. the relvant labels would be codegen'd as abstract classes in application code. Additionally, it conveys intention to anyone looking at the schema, so it's good as a form of documentation.

Not a hugely important feature in my opinion, but would be a nice to have in the future if it's relatively simple to implement.

Thanks for your time!
John

**Comment by kskim80** [comment]
Thank you for your suggestion.
We will consider the feature to be included in the next release.

**Comment by toraritte** [comment]
Hi @johnberzy-bazinga, 

would this result in a similar functionality to Neo4j's multiple tagging?

For example, if a vertex would represent organizations, it would have an Organization superclass with different subclasses, such as Educational (with further subclasses), GovernmentAgency, Services etc but many of these could be either commercial or non-profit. With Neo4j, I would just put extra labels but I am not sure with AgensGraph.

```
Organization --> Educational --> University
      \                     \--> High School
       \
        \--> Services --> Outpatient
                     \--> Telecommunications

Any of these could be either a non-profit or a commercial outfit.
```
I know, there are many options, such as

- let Nonprofit or Commercial dangle at the end of the chain and just follow the ancestry

- put a "type" attribute in the vertex
- create extra "type" vertexes to point to
- etc.
but I was wondering if this would be a legitimate use case.

Thank you!
Attila

**Comment by johnberzy-bazinga** [comment]
@toraritte I believe what you're referring to can be achieved with multiple-inheritance which seems to be [already supported](https://github.com/bitnine-oss/agensgraph/blob/90d2ebfc25e92e2f77811e577de04b1b505d325e/src/test/regress/expected/cypher_ddl.out#L75).

This feature might help in circumstances where you'd like to enforce not instantiating a "non-profit" or "commercial" vertex. The workaround is to just add checks in application code or perhaps adding a check-constraint in the appropriate backing table  for that v/e label  (although I'm not sure how how that interacts with agens) e.g. `CONSTRAINT nonprofit_abstract_check CHECK (false) NO INHERIT`.

**Comment by emotionbug** [comment]
Closes old issues.
