### ISSUE TITLE
find root or leaf nodes

### ISSUE THREAD

**Issue by mrft** [bitnine-oss/agensgraph#167]
Googling tels me that in order to find the 'root' for a certain node somewhere in a tree you should use a query like

```
MATCH (:organisationalunit {name: 'Team ICT'})-[:is_part_of *]->(root:organisationalunit)
WHERE NOT ( (root)-[:is_part_of]->() )
RETURN root::text
```

but this one tells me

`Error: ERROR: syntax error at or near "["
  Position: 110
SQLState:  42601
ErrorCode: 0`

**Comment by protodef** [comment]
You can use a slightly modified query like
```
MATCH (:organisationalunit {name: 'Team ICT'})-[:is_part_of *]->(root:organisationalunit)
WHERE NOT EXISTS ((root)-[:is_part_of]->())
RETURN root::text
```

**Comment by kskim80** [comment]
I close this issue.
