### ISSUE TITLE
Friends of friends query is not working

### ISSUE THREAD

**Issue by henrymana** [bitnine-oss/agensgraph#191]
I cloned and compiled master... but I am not able to get the friends of friends query working... This is my test data and query. I am using macos Sierra.

my_graphdb=# MATCH (n:person)-[:knows]->(m:person) RETURN n.name AS n, m.name AS m;
   n   |   m    
-------+--------
 Tom   | Summer
 Pat   | Nikki
 Olive | Todd
 Tom   | Summer
 Pat   | Nikki
 Olive | Todd
(6 rows)

my_graphdb=# CREATE (:person {name: 'Summer'})-[:knows]->(:person {name: 'Nikki'});
GRAPH WRITE (INSERT VERTEX 2, INSERT EDGE 1)
my_graphdb=# CREATE (:person {name: 'Summer'})-[:knows]->(:person {name: 'Todd'});
GRAPH WRITE (INSERT VERTEX 2, INSERT EDGE 1)
my_graphdb=# 
my_graphdb=# MATCH (n:person)-[:knows]->(m:person) RETURN n.name AS n, m.name AS m;
   n    |   m    
--------+--------
 Tom    | Summer
 Pat    | Nikki
 Olive  | Todd
 Tom    | Summer
 Pat    | Nikki
 Olive  | Todd
 Summer | Nikki
 Summer | Todd
(8 rows)

my_graphdb=# MATCH (p:person {name: 'Tom'})-[:knows]->()-[:knows]->(f:person) RETURN p.name AS n, f.name AS m;
 n | m 
---+---
(0 rows)

**Comment by gtyun** [comment]
Hi, @henrymana 

> my_graphdb=# CREATE (:person {name: 'Summer'})-[:knows]->(:person {name: 'Nikki'});
GRAPH WRITE (**INSERT VERTEX 2**, INSERT EDGE 1)
my_graphdb=# CREATE (:person {name: 'Summer'})-[:knows]->(:person {name: 'Todd'});
GRAPH WRITE (**INSERT VERTEX 2**, INSERT EDGE 1)

This query creates new 'Summer' vertex every time. So there are four 'Summer' vertex in your graph and they have only one relationships.
If you want to create only relationship with existing 'Summer' and 'Nikki', you can try this.
`MATCH (a:person {name:'Summer'}), (b:person {name:'Nikki'}) CREATE (a)-[:knows]->(b);`
`GRAPH WRITE (INSERT EDGE 1)`

My suggestion is following block.
>ygt=# create vlabel person;
CREATE VLABEL
ygt=# create elabel knows;
CREATE ELABEL
ygt=# create (:person {name:'Tom'})-[:knows]->(:person {name: 'Summer'});
GRAPH WRITE (INSERT VERTEX 2, INSERT EDGE 1)
ygt=# create (:person {name:'Pat'})-[:knows]->(:person {name: 'Nikki'});
GRAPH WRITE (INSERT VERTEX 2, INSERT EDGE 1)
ygt=# create (:person {name:'Olive'})-[:knows]->(:person {name: 'Todd'});
GRAPH WRITE (INSERT VERTEX 2, INSERT EDGE 1)
ygt=# MATCH (n:person)-[:knows]->(m:person) RETURN n.name AS n, m.name AS m;
   n   |   m    
-------+--------
 Tom   | Summer
 Pat   | Nikki
 Olive | Todd
(3 rows)
ygt=# match (a:person {name:'Summer'}), (b:person {name:'Nikki'}) create (a)-[:knows]->(b);
GRAPH WRITE (INSERT EDGE 1)
ygt=# MATCH (p:person {name: 'Tom'})-[:knows]->()-[:knows]->(f:person) RETURN p.name AS n, f.name AS m;
  n  |   m   
-----+-------
 Tom | Nikki
(1 row)

Thank you.

**Comment by henrymana** [comment]
Apologies for opening an issue, I'll close the issue and try what you suggest. Thank you.
