### ISSUE TITLE
Implement a weighted shortest path

### ISSUE THREAD

**Issue by mlogue** [bitnine-oss/agensgraph#196]
Implement dijkstra's algorithm to get the shortest path between two nodes

**Comment by mlogue** [comment]
Status: Review & Design

**Comment by mlogue** [comment]
* writing design document [[link](https://docs.google.com/document/d/1jjOec7VkoUh1Afvz5y2w9opSep15055I5aha-xk-5cw/edit#heading=h.upxjymcl11ls)]
* reviews hash join code

**Comment by mlogue** [comment]
Studying http://workshop.pgrouting.org/2.1.0-dev/en/index.html

**Comment by mlogue** [comment]
Review pgr_dijkstra() and pgr_bdDijkstra() in pgRouting

**Comment by mlogue** [comment]
I've started to design and implement for all-in-memory cases
* Query to get neighbor vertices
* Hash structure for cost and path
* Min queue for finding a minimum cost vertex

**Comment by mlogue** [comment]
I'm implementing dijkstra's algorithm in ExecNode
* using HTAB and pairingheap

**Comment by mlogue** [comment]
I'm implementing dijkstra() grammar and transformation.

**Comment by archenroot** [comment]
Was it implemented?
