### ISSUE TITLE
Cannot refer to vertex attributes

### ISSUE THREAD

**Issue by htlim** [bitnine-oss/agensgraph#197]
Can not refer to the attributes of the vertices you created in the previous clause.

`create (a {name:'a'}) create (b {prop:a.name});`
`ERROR:  missing FROM-clause entry for table "a"`

**Comment by htlim** [comment]
In the process of transforming Expr for the 'Properties' column, variables of the same clause are not yet registered in the pstate's parsenamespace, so an error occurs because the object to be referenced can not be found.

**Comment by gtyun** [comment]
Moved to trello
