### ISSUE TITLE
Build Agensgraph in Windows

### ISSUE THREAD

**Issue by gtyun** [bitnine-oss/agensgraph#200]
Create binary of Agensgraph for windows and provide installer with BitRock.

**Comment by gtyun** [comment]
ref : https://www.postgresql.org/docs/9.6/static/install-windows-full.html

postgresql
- successfully built and passed regression test

agensgraph
- occur compile error. The logs are following attached file.
Trying to figure out the cause.

[build_log_full.txt](https://github.com/bitnine-oss/agensgraph/files/912234/compile_full.txt)
[build_log_err.txt](https://github.com/bitnine-oss/agensgraph/files/912236/compile_err.txt)

**Comment by gtyun** [comment]
>C:\working_space\agensgraph\v1.1.0\src\backend\parser/gram.h(309): error C2059: syntax error : '=' (src/backend/parser/scan.c) [C:\working_space\agensgraph\v1.1.0\postgres.vcxproj]

gram.h

enum yytokentype {
    IDEN = 258,
    ...
    ...
    OPTIONAL = 526,     <<< line 309, why syntax error??
    ...
}


>src/backend/parser/parser.c(116): error C2065: 'WITH' : undeclared identifier [C:\working_space\agensgraph\v1.1.0\postgres.vcxproj]
src/backend/parser/parser.c(165): error C2065: 'SIMILAR' : undeclared identifier [C:\working_space\agensgraph\v1.1.0\postgres.vcxproj]
...

WITH, SIMILAR is declared in gram.h


>C:\working_space\agensgraph\v1.1.0\src\include\parser/kwlist.h(282): error C2059: syntax error : ',' (src/common/keywords.c) [C:\working_space\agensgraph\v1.1.0\postgres.vcxproj]

The other errors are caused by first error with "OPTIONAL".

**Comment by kskim80** [comment]
@gtyun please upload gram.h file too.

**Comment by gtyun** [comment]
*.h is not supported, so I attached zipped gram.h.

[gram.zip](https://github.com/bitnine-oss/agensgraph/files/914994/gram.zip)

**Comment by gtyun** [comment]
src/port/win32ver.rc is necessary but missing

The syntax error resolved by replacing symbol 
"OPTIONAL" to "OPTIONAL_P" and "SIZE" to "SIZE_P"

Now the compile error message says "libpq-fe.h" is missing.

**Comment by gtyun** [comment]
src/bin/ag_ctl,
src/bin/agens 
: Cannot open include file: 'libpq-fe.h': No such file or directory
: Cannot open include file: 'win32.h': No such file or directory
...

src/backend/utils/adt/graph.c(115): error C2065: 'int8in' : undeclared identifier 

Above 2 module and 1 file cannot find there header file. Other modules share their environmental variables. For example, psql is almost same with agens. But only new modules occur problems.

**Comment by gtyun** [comment]
Fix Mkvcbuild.pm for module 'agens', 'ag_ctl' to find adjust header.
Add the modules to array '@frontend_uselibpq'

AG_VERSION must be defined in pg_config.h
Add definition to pg_config.in.win32.

Now sql_help.c, sql_help.h is missing.

**Comment by gtyun** [comment]
pgsqlscanslach.c can be created by Mkvcbuild.pm with $frontend_extrasource.

**Comment by gtyun** [comment]
Fix src/backend/utils/adt/graph.c. 
Add this line
>#include "utils/int8.h"

Why this file was compiled properly in Linux..? and why not in Windows?

Anyway Agensgraph complie success without contrib modules(pg_statsinfo, hadoop_fdw, pg_hint_plan, postgresql-hll is removed )


But regress test fails..
cypher_dml , cypher_ddl, sql_restriction, propertyindex.

**Comment by gtyun** [comment]
CREATE GRAPH occurs FATAL error.

> LOG:  server process (PID 11420) was terminated by exception 0xC0000005
DETAIL:  Failed process was running: CREATE GRAPH g;
HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
LOG:  all server processes terminated; reinitializing
LOG:  database system was interrupted; last known up at 2017-04-14 17:22:49 KST
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  redo starts at 0/1534C00
LOG:  could not stat file "pg_tblspc/16386": No such file or directory
CONTEXT:  xlog redo at 0/1534C00 for Tablespace/DROP: 16386
FATAL:  the database system is in recovery mode

Attached file is full log of regression test.
[postmaster.txt](https://github.com/bitnine-oss/agensgraph/files/921790/postmaster.txt)

**Comment by gtyun** [comment]
0xC0000005 of nstatus.h

//
// MessageId: STATUS_ACCESS_VIOLATION
//
// MessageText:
//
// The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s.
//
#define STATUS_ACCESS_VIOLATION          ((NTSTATUS)0xC0000005L)    // winnt

**Comment by gtyun** [comment]
FATAL error point is..
create graph
-> create label
-> transformLabelIdDefinition
{
...
#ifdef HAVE_LONG_INT_64
    maxval = makeDefElem("maxvalue", (Node *) makeInteger(GRAPHID_LOCID_MAX));
#else
    {    
        char *buf[32];

        snprintf(buf, UINT64_FORMAT, GRAPHID_LOCID_MAX);
        maxval = makeDefElem("maxvalue", (Node *) makeFloat(pstrdup(buf)));
    }    
#endif

It's a 64 bit system but the code runs for 32 bit.

**Comment by gtyun** [comment]
We found that is not a system bit problem, just a code error.
The code fixed like this
> char buf[32];
snprintf(buf, sizeof(buf), UINT64_FORMAT, GRAPHID_LOCID_MAX);

Now regression test all passed.
I made a [branch](https://github.com/gtyun/agens-graph/commits/build_on_windows) and push on my fork repository.

**Comment by gtyun** [comment]
Instead of removing un-buildable contrib modules, they are added to '@contrib_excludes' array in Mkvcbuild.pm.
