### ISSUE TITLE
Automatically create labels

### ISSUE THREAD

**Issue by roelj** [bitnine-oss/agensgraph#210]
Would it be possible to automatically create `VLABEL`s and `ELABEL`s upon first usage of them in a query?

**Comment by kskim80** [comment]
@roelj We've implemented this recently. #204 
Thanks.

**Comment by roelj** [comment]
Thanks for the quick reply.

Sorry for the duplicate, and great to see it has already been implemented :+1:

**Comment by kskim80** [comment]
Thank you for your interests on AgensGraph!
If you have more suggestions, please let us know anytime.
