### ISSUE TITLE
create homebrew package?

### ISSUE THREAD

**Issue by AlJohri** [bitnine-oss/agensgraph#220]
would be easier to try this out locally on macOS if there was a homebrew package. https://brew.sh/

thanks!

**Comment by shayneoneill** [comment]
nearly 3 years without even an answer. Their "download" link points to a youtube with a presenter who's accent I struggle to understand. I don't think they want mac users.

**Comment by emotionbug** [comment]
@shayneoneill yeah, we missed this. I'll look into it.

**Comment by emotionbug** [comment]
duplicate with #220
