### ISSUE TITLE
Installtion question- Is postgresql needs to be installed before agensgraph

### ISSUE THREAD

**Issue by graphtest123** [bitnine-oss/agensgraph#221]
I am new to PostgreSQL and agensgraph and having rough time to setup the environment. 

 Is PostgreSQL needs to be installed before agensgraph? If PostgreSQL included in AgensGraph, can I use PgAdmin with AgensGraph?

Thanks
Krishna

**Comment by gtyun** [comment]
PostgreSQL is included in AgensGraph, so pre-installation is not needed.
You can use PgAdmin also freely.
Sorry for my late response.
