### ISSUE TITLE
Questions regarding LDBC benchmark

### ISSUE THREAD

**Issue by pawanrawal** [bitnine-oss/agensgraph#250]
I read http://www.businesswire.com/news/home/20170629005344/en/Graph-DBMS-Performance-Comparison-AgensGraph-vs.-Neo4j. Great work guys! I have some questions.

1. What indexes were created for Neo4j? This link https://github.com/kskim80/ldbc-snb-impls/blob/master/snb-interactive-neo4j/src/main/java/net/ellitron/ldbcsnbimpls/interactive/neo4j/Neo4jDb.java doesn't work.
2. What scale factor were these benchmarks run with?

**Comment by johnberzy-bazinga** [comment]
@pawanrawal 

I'm not sure about scale factor, but I believe the link you're looking for it this:

https://github.com/bitnine-oss/ldbc-snb-impls/blob/master/snb-interactive-neo4j/src/main/java/net/ellitron/ldbcsnbimpls/interactive/neo4j/Neo4jDb.java

**Comment by gtyun** [comment]
1. The definition of indexes are here. This script is written by PlatformLab. 
https://github.com/bitnine-oss/ldbc-snb-impls/blob/master/snb-interactive-neo4j/scripts/indexCreation.neo4j

2. We tested with Scale Factor 30.
