### ISSUE TITLE
questions about agensgraph

### ISSUE THREAD

**Issue by candysmurf** [bitnine-oss/agensgraph#256]
Only a couple of questions now and I'll have more questions to follow. thanks.

- is agensgraph can be deployed in a 3 nodes PostgreSQL cluster?
- are there HTTP APIs for client access?
- is there a visualizer?
- who are your clients?

**Comment by gtyun** [comment]
- A replication cluster is possible. You can apply the postgreSQL manual as it is.
- Not yet supported, but planning.
- The visualizer is 'Agens Browser'. Alpha version is working on. It will not be an open source project, maybe.
- I do not know that I can tell about clients.

**Comment by candysmurf** [comment]
May I know:

- if the cluster is master-slave or master-slave-slave?
- Is the `agens browser` accessible now? May I try it?
- Were you say that you don't have any customers?

**Comment by gtyun** [comment]
- Both clusters are possible. We did not touch replication part of PostgreSQL.
- Unfortunately, not opened to the public.
- Some clients exists. That's all what can I say now.

Thank you for your interest.

**Comment by candysmurf** [comment]
May I know how I can use your `agens browser`? Any purchase plan available? What's your roadmap?

**Comment by joshuayb** [comment]
Hi Candy,

- I'm with AgensGraph. We do have clients in several different areas such as Smart Factory solutions, Retail Business, Fintech and Cyber Attack Detection. We can give you more details.
- We are internally reviewing AgensBrowser which is v0.7, not generally available. However, we can visit you and provide a demonstration session. That will give you the idea how it works, key differentiators from other graph visualization tools.

Our R&D Center is in Santa Clara. I think we are 15 min driving distance at most. Please, give me an e-mail and then we can schedule a meeting. (or a video conference)

Thanks.

**Comment by candysmurf** [comment]
@joshuayb, I saw that you guys will demo this to us today. thanks for your reply.

**Comment by joshuayb** [comment]
Hi Emily,

Yes, I assumed you might be in the meeting today. It was nice to talk with you all. Feel free to contact me anytime if you have any questions. joshua@bitnine.net

**Comment by candysmurf** [comment]
May I know what client do you support? Java for sure. Any others?

**Comment by gtyun** [comment]
Only java is supported for now. Python and Node.js are planned.

**Comment by candysmurf** [comment]
@gtyun,thanks for your reply. I'll give Java a try.

**Comment by candysmurf** [comment]
May I install 3 instances on the same machine to form a cluster? Any guideline/example?

**Comment by gtyun** [comment]
If you want to make a replication cluster, you can refer to https://www.postgresql.org/docs/9.6/static/warm-standby.html
https://wiki.postgresql.org/wiki/Streaming_Replication

If each instance has its own PGPORT, it's possible that 3 instance on the same machine. Actually I 
 tested with virtual box. 
The Following is brief description for hot standby server configuration.

- Master(primary) instance setup
Add to pg_hba.conf
host	replication	‘username_primary’	‘ip address_standby’	trust
host	replication	‘username_standby’	‘ip address_primary’	trust

Fix postgresql.conf
listen_address = '*'
wal_level = 'hot_standby'
max_wal_senders = 4
wal_keep_segments = 64
hot_standby = on
max_replication_slots = 1

- Slave(secondary) instance setup
Copy master's database 
cd $AGENS_HOME
mkdir -m 700 /data
pg_basebackup -h hostip -U username -D data -R

Fix ./data/recovery.conf
recovery_target_timeline = 'latest'
primary_slot_name = 'rp_slot_name'
Add "application_name=slave1" to primary_conninfo

**Comment by candysmurf** [comment]
@gtyun, thanks for your reply. I was busy doing other stuff. Now I really need to get this going.
Where are pg_hba.conf and postgresql.conf files? I don't see them.

Any docker cluster setup do you have?

**Comment by gtyun** [comment]
That conf files are in the directory where you have initialized database byfollowing command.
 'initdb -D /path/to/datadir'
Or if you set $AGDATA, than conf files will be there after initdb.
Unfortunately, docker image is not ready yet.

**Comment by gtyun** [comment]
@candysmurf ,
I'm going to build docker image for AgenGraph and @joshuayb will contact to you about the work sesstion

**Comment by johnberzy-bazinga** [comment]
@gtyun @candysmurf  If it's any help I've modified the official postgres docker image a while back to work with agens. I've only been using it locally, so have not vetted it for production use. Also, I've removed the hadoop from the list of extensions as I could not get it to work.

https://gist.github.com/johnberzy-bazinga/b89e39f105b0ac3a962b97ccac200cfd

usage (with no persistent volume) : 

`docker build -t agensgraph .`

`docker run --rm -p 5432:5432 -e POSTGRES_DB='testdb' agensgraph:latest`

**Comment by johnberzy-bazinga** [comment]
Also, I've added experimental client support for .NET on top of Npgsql if interested.

https://github.com/johnberzy-bazinga/Npgsql.AgensGraph

**Comment by candysmurf** [comment]
@johnberzy-bazinga, thanks for your docker image. It's one instance though. I need to build the stream replication agensgraph 3 nodes cluster. Can we turn this to use docker-compose on different ports on the same machine?

**Comment by candysmurf** [comment]
@gtyun, I'm trying to setup two nodes first on the same machine using different ports. As they're on the same machine with different ports. Do I stil need to add the following:

Add to pg_hba.conf
host	replication	‘username_primary’	‘ip address_standby’	trust
host	replication	‘username_standby’	‘ip address_primary’	trust

Leaving ip address empty? As I didn't setup a username yet, leaving them empty as well?

**Comment by candysmurf** [comment]
if I execute the following statement, it returned 0 rows.
```
vagrant@ubuntu1604:~$ agens -p 5433 test
agens (AgensGraph 1.2.0, based on PostgreSQL 9.6.2)
Type "help" for help.

test=# select * from pg_stat_replication;
 pid | usesysid | usename | application_name | client_addr | client_hostname | client_port | backend_start | backend_xmin | state | sent_location | write_location | flush_loc
ation | replay_location | sync_priority | sync_state
-----+----------+---------+------------------+-------------+-----------------+-------------+---------------+--------------+-------+---------------+----------------+----------
------+-----------------+---------------+------------
(0 rows)

```

**Comment by gtyun** [comment]
my pg_hba.conf is 
host    replication     ygt        127.0.0.1/32            trust

'replica' is your agensgraph user name?
And you don't need to write twice. But it does not matter anyway.

And in master session
test=# SELECT * FROM pg_create_physical_replication_slot('rp_slot_name');

Everything else looks fine.

My result is ...
[ygt@ygtpc agens-graph]$ ps x | grep postg
 3603 pts/2    S      0:00 /home/ygt/work/git/agens-ygt/AgensGraph/bin/postgres
 3611 ?        Ss     0:00 postgres: checkpointer process   
 3612 ?        Ss     0:00 postgres: writer process   
 3613 ?        Ss     0:00 postgres: wal writer process   
 3614 ?        Ss     0:00 postgres: autovacuum launcher process   
 3615 ?        Ss     0:00 postgres: stats collector process   
 3993 pts/2    S      0:00 /home/ygt/work/git/agens-ygt/AgensGraph/bin/postgres -D old -p 5433
 3994 ?        Ss     0:00 postgres: startup process   recovering 000000010000000000000012
 3995 ?        Ss     0:00 postgres: wal receiver process   streaming 0/12000060
 3996 ?        Ss     0:00 postgres: wal sender process ygt 127.0.0.1(40360) streaming 0/12000060
 3998 ?        Ss     0:00 postgres: checkpointer process   
 3999 ?        Ss     0:00 postgres: writer process   
 4000 ?        Ss     0:00 postgres: stats collector process   
 4009 pts/2    S+     0:00 grep --color=auto postg
[ygt@ygtpc agens-graph]$ agens
agens (AgensGraph 1.2.0, based on PostgreSQL 9.6.2)
Type "help" for help.

ygt=# select * from pg_stat_replication ;
 pid  | usesysid | usename | application_name | client_addr | client_hostname | client_port |         backend_start         | backend_xmin |   state   | sent_location | write_location | flus
h_location | replay_location | sync_priority | sync_state 
------+----------+---------+------------------+-------------+-----------------+-------------+-------------------------------+--------------+-----------+---------------+----------------+-----
-----------+-----------------+---------------+------------
 3996 |       10 | ygt     | slave1           | 127.0.0.1   |                 |       40360 | 2017-11-02 18:28:34.072319+09 |              | streaming | 0/12000060    | 0/12000060     | 0/12
000060     | 0/12000060      |             0 | async
(1 row)

**Comment by candysmurf** [comment]
@gtyun, yes, `replica` is the replication user created.
after I change `md5` to `trust`, when doing select, I got

```
test=# SELECT * FROM pg_create_physical_replication_slot('rp_slot_name');
ERROR:  replication slot "rp_slot_name" already exists
```

Also my output is different than yours
```
vagrant@ubuntu1604:~$ ps x | grep postg
13148 pts/0    S      0:00 /share/agensgraph/bin/postgres -D db_cluster
13150 ?        Ss     0:00 postgres: checkpointer process
13151 ?        Ss     0:00 postgres: writer process
13152 ?        Ss     0:00 postgres: wal writer process
13153 ?        Ss     0:00 postgres: autovacuum launcher process
13154 ?        Ss     0:00 postgres: stats collector process
13158 pts/0    S      0:00 /share/agensgraph/bin/postgres -D db_cluster_1
13160 ?        Ss     0:00 postgres: checkpointer process
13161 ?        Ss     0:00 postgres: writer process
13162 ?        Ss     0:00 postgres: wal writer process
13163 ?        Ss     0:00 postgres: autovacuum launcher process
13164 ?        Ss     0:00 postgres: stats collector process
13173 pts/0    S+     0:00 grep --color=auto postg
```
Maybe something is still missing?

**Comment by candysmurf** [comment]
Note that as I have two instances on the same server, i have to login the master using this command:

```
agnes -p 5433 test
```
Which is one of DB in the master instance.

**Comment by candysmurf** [comment]
@gtyun, what command did you use to init two instances on the same machine? I'm wondering if there are differences between yours and mine.

**Comment by gtyun** [comment]
That ps x output shows that your both sessions are master.
The recovery.conf must be in slave's db_cluster to start up as slave.

command for my master session 
ag_ctl start -w -D ./data -o "-p 5432"

command for my slave session
ag_ctl start -w -D ./old -o "-p 5433"

both username is ygt and dbname is ygt

**Comment by candysmurf** [comment]
@gtyun, I created data directory inside db_cluster_1 which is slave. The recovery.conf generated after running pg_backup. 

Does it require the dbname and username to be same?

Maybe I should try your -o command option to see if it makes any difference.

**Comment by gtyun** [comment]
dbname and username do not have to be the same.
And postgres.conf has been replicated and not modified.

**Comment by candysmurf** [comment]
@gtyun, mine two instances are like master/master. I don't know what I'm missing. May I have a meeting with you tonight?

**Comment by gtyun** [comment]
@candysmurf 
The master's data directory is initiated by 'initdb' command. It's the path '$AgensHome/data' in my case.
And slave's data directory is created by 'mkdir' and filled by 'pg_basebackup'. It's '$AgensHome/old' in my case.

**Comment by candysmurf** [comment]
@gtyun, nevermind. I made it work now. The part I did differently is that I didn't mkdir `data` directory and also I had to use `replica` as the wal_level, such as wal_level=replica in the master.

I bet that I can use the same way to create as many slaves as I like. 

It's confusing to me as I didn't have postgres background. Anyway, thank you.

**Comment by gtyun** [comment]
@candysmurf Sounds great. Good work.

**Comment by candysmurf** [comment]
@gtyun, next question is that if the master is down, I would like to promote one of the slaves to be the master then restart master automatically. Anything do you recommend? thanks

**Comment by gtyun** [comment]
@candysmurf 
You can promote manually like following command
ygt=# ag_ctl promote -D $slave_data
ygt=# ag_ctl restart -D $slave_data

If you want to build a high availability cluster with auto failover, yon can reference https://clusterlabs.github.io/PAF/ .

Building HA cluster is much more complicated. It was painful for me to do that...

**Comment by candysmurf** [comment]
@gtyun, ah. Thanks.

If we don't build that, how do you know a master is down and need to promote a slave? When restarting the master, any agnes's command or I need to alter the parameters?

**Comment by gtyun** [comment]
@candysmurf 
If master is down, than all kind of connection must be failed. You need to check status of master periodically. PAF used pacemaker for checking.
When a slave is promoted to a master, parameter modification is not required. Just the recovery.conf must be removed. If promotion was successful, it will removed automatically. 
But you must check connection information. Because slave has different ip address or port.

**Comment by candysmurf** [comment]
@gtyun, any feature is out of the box of AG to check the master? I just don't want to miss anything which is available. Or we'll have to use PAF or...

**Comment by gtyun** [comment]
@candysmurf 
If you must build HA cluster, you should just use PAF. Postgresql does not support auto failover by itself.

**Comment by candysmurf** [comment]
@gtyun, for modeling nested JSON objects, eg.

Object {
   "name": "a",
   "stauts": {
        "state": "on"
         ....
    }
}

Agensgraph seems only support primitive types plus array. `status` will have to model as a vertex.   Is it right?

**Comment by gtyun** [comment]
Yes, it is JSONB. Sure JSON and JSONB is almost identical.
JSONB supports primitive types and JSONB object and array.

**Comment by candysmurf** [comment]
I tried to save it as JSONB. I always got an error:

First:
```
JSONObject jstatus = new JSONObject();
jstatus.put("status", jstatus);
```

Second
```
Jsonb statusJson = new JsonbObjectBuilder().add("status", status).build();
```

Error:
```
java.lang.IllegalArgumentException: Invalid json value type
	at net.bitnine.agensgraph.util.JsonbUtil.filterValueType(JsonbUtil.java:148)
	at net.bitnine.agensgraph.util.JsonbObjectBuilder.add(JsonbObjectBuilder.java:63)
	at com.javasampleapproach.jdbcpostgresql.dao.impl.FMSVertexDaoImpl.insert(FMSVertexDaoImpl.java:79)
	at com.javasampleapproach.jdbcpostgresql.dao.impl.FMSVertexDaoImpl$$FastClassBySpringCGLIB$$3c333562.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at com.javasampleapproach.jdbcpostgresql.dao.impl.FMSVertexDaoImpl$$EnhancerBySpringCGLIB$$1b6fdd8.insert(<generated>)
	at com.javasampleapproach.jdbcpostgresql.service.impl.FMSVertexServiceImpl.insert(FMSVertexServiceImpl.java:23)
	at com.javasampleapproach.jdbcpostgresql.SpringJdbcTemplatePostgreSqlApplication.main(SpringJdbcTemplatePostgreSqlApplication.java:47)
```

**Comment by candysmurf** [comment]
JSONB seems not searchable.  e.g. if I have data like 

```
system[3.4]{"id": "8888", "name": "we", "ctype": "type B", "status": {"health": "good"}}
```

Cypher query got an error.

```
match(s:system{status.health: 'good'}) return s;
```
Please let me know if I miss anything.

**Comment by gtyun** [comment]
Then this will work well.
`match(s:system { status : {health: 'good' }}) return s;

**Comment by candysmurf** [comment]
@gtyun, thanks for your help, it worked! How to find all nodes that have no relationship?

```
graph=# start n=node(*) match(n)-[r?]-() where r is null return n;
ERROR:  syntax error at or near "n"
LINE 1: start n=node(*) match(n)-[r?]-() where r is null return n;
```

**Comment by gtyun** [comment]
That question is interesting. I didn't think about the vertex without edges..
You can get that vertex like following.

`MATCH (a), (b)-[r]-(c)
WHERE a != b and a != c
RETURN a`

**Comment by yinmingjun** [comment]
I try to use like in match-where cause, and I got an error of "...unknown like...".

The cypher I had tested like this:
match (a:label_a)
where a.name like '%mk%'
return a;

How should I do like this?
Or another similiar way is also  welcomed!

**Comment by joshuayb** [comment]
Your query is supposed to work. I don't see any syntax error there.
I think we need to see the actual screenshot to help you.
We may do a quick shared screen call if that helps.
Let me send you an e-mail shortly.

**Comment by yinmingjun** [comment]
@joshuayb You can see the issue here: #288 
Thanks.

**Comment by joshuayb** [comment]
Thank you for sharing the issue.

**Comment by candysmurf** [comment]
@gtyun, one last question before we close this issue. Everything works well except that merge operation does not detect the duplicates.

For example, I want to save a vertex(node), it's an object which has a property id=10. By using merge, if I save the object with the same id, should it detect it and just update the object instead of creating a duplicate? Please advise if I miss anything. Your timely response is greatly appreciated. We'll have a demo this Friday.

**Comment by johnberzy-bazinga** [comment]
@candysmurf 

The following query works for me :

```CREATE VLABEL Person;

MERGE (p:Person {email : 'john@example.com'})
ON CREATE SET p.created = true
ON MATCH SET p.merged = true
RETURN p.email, p.created, p.merged;```

Also, if you need to ensure no duplicates, you can add a unique property index 
```CREATE UNIQUE PROPERTY INDEX ON Person (email);```

**Comment by candysmurf** [comment]
@johnberzy-bazinga, thanks for the quick response. What I found is that if all properties for a person is identical, MERGE won't create a new one, when one of the properties is different, MERGE creates a new one although the Java object equal method only specified ID is the determining fact of if two objects are the same.

If I create the unique index, will it throw an exception if the same ID used with different property value? I would like the intelligence of agensgraph to know if ID exists, update it, otherwise create it. Is it possible?

**Comment by johnberzy-bazinga** [comment]
@candysmurf I don't think it works like that. If I'm not mistaken, you'll need to set the non-unique properties in the `ON CREATE/MATCH SET` clauses.

**Comment by candysmurf** [comment]
@johnberzy-bazinga, do you have an update operation example? If I have many properties, do I need to set all of them one by one? Why can agensgraph just update the node? 

Did you mean that I need to make multiple DB calls? first is to find if it exists, if it exists, update, otherwise create?

**Comment by johnberzy-bazinga** [comment]
> Did you mean that I need to make multiple DB calls? first is to find if it exists, if it exists, update, otherwise create?

No, because that would defeat the purpose of Merge.

You could do something like this I think :

````
MERGE (p:Person {id : 'john@example.com'})
SET p += {age : '23'}
RETURN p;
```

**Comment by candysmurf** [comment]
@johnberzy-bazinga, the input is an object. I don't know which field/property is changed unless I get the one inside DB out and compare them. Any other way to do an object update?

**Comment by johnberzy-bazinga** [comment]
@candysmurf 

If I understand you correctly, what you want to do is merge based on the unique id, and append all the additional properties of your input object, correct? In that case, what I sent should work. I'm not sure what driver you're using, but you should be able to parameterize the query to accept the input object. i.e.

```
MERGE (p:Person {id : 'john@example.com'})
SET p += ?
RETURN p; 
```

**Comment by candysmurf** [comment]
@johnberzy-bazinga, not necessary adding a new property but update a few existing property, example query, please. thanks

**Comment by candysmurf** [comment]
@johnberzy-bazinga, yes the query you gave worked except I removed the + sign. Than you very much for your help!

**Comment by johnberzy-bazinga** [comment]
@candysmurf Without the `+=` operator you'll completely replace the existing properties instead of merging them.

**Comment by candysmurf** [comment]
@johnberzy-bazinga, ah, you meant the merge is a better operation. Thanks for the tip. I'm using += operation now.

**Comment by candysmurf** [comment]
@gtyun & @johnberzy-bazinga, thanks for all your help. Our demo went very well. Everything worked nicely. I'm going to close this issue and open a new one to a couple more questions.

**Comment by pratikpparikh** [comment]
@candysmurf did you create a docker swarm configuration for your experiment? If so can you please share?
