### ISSUE TITLE
linux64 binary does not work on Linux x86_64

### ISSUE THREAD

**Issue by candysmurf** [bitnine-oss/agensgraph#257]
when ran the command `initdb -D ...` command, the output
```
AgensGraph/bin/postgres: error while loading shared libraries: libplds4.so: cannot open shared object file: No such file or directory
no data was returned by command ""/usr/local/AgensGraph/AgensGraph/bin/postgres" -V"
The program "postgres" is needed by initdb but was not found in the
same directory as "/usr/local/AgensGraph/AgensGraph/bin/initdb".
Check your installation.
```
my server is
```
$ uname -a
Linux ess-data 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by candysmurf** [comment]
The binary dependents on different Linux distributions. The downloadable binary does not work on Ubuntu. I had to build it from the source.

**Comment by jbrumwell** [comment]
I'm running into the same issue with the binary, and building from source I get the following issue;

```
#> make install-world
...
error /usr/bin/ld: cannot find -ljvm
```

libjvm.so is in the LD_LIBRARY_PATH, even tried symlink it in agens lib directory. Is there a plan to release as a docker container?  We are experimenting with removing neo4j from our stack and consolidating into agensgraph.

**Comment by gtyun** [comment]
Export LIBRARY_PATH=/path/to/jvm

**Comment by gtyun** [comment]
I miss clicked. 
Please try with LIBRARY_PATH, not LD_LIBRARY_PATH.
We made personal docker image of AgensGraph but not official, it will come in near future.

**Comment by jbrumwell** [comment]
That worked thank you :)
