### ISSUE TITLE
Arrays not supported as properties?

### ISSUE THREAD

**Issue by jbrumwell** [bitnine-oss/agensgraph#260]
The following fails

`CREATE (:LABEL {`email`:"...", `firstName`:"bing", `lastName`:"bab", `phone`:"2342342324", `tags`:[], uniqueImportId:183 });`

with error `ERROR:  syntax error at or near "["`

**Comment by bravius** [comment]
I had the same problem, you can get around it by using SET to create an Array property:

`CREATE (a:LABEL {}) SET a.tags='["one","two","three"]' return a;`

**Comment by gtyun** [comment]
Array was not supported because of parser issue. Now that is resoleved so you can use array in master branch or v1.3.0(release soon)
