### ISSUE TITLE
AgensGraph postgres extension

### ISSUE THREAD

**Issue by ghost** [bitnine-oss/agensgraph#268]
I'm interested in working with AgensGraph and Cypher for graph functionality; the demos look really cool!  

I'm somewhat nervous about the overhead of switching to a new DBMS from Postgres, however. I've found Postgres extensions like PostGIS etc. very effective in providing the functionality without much overhead. 

Given your expertise in Postgres' tech, do you think it would be possible to offer an AgensGraph extension for Postgres? Is my intuition correct that this would be the easiest (from the user's perspective) way to get sophisticated graph functionality in a postgres database? Thanks!

**Comment by auvipy** [comment]
considering the fact, citusdb recently converted their forks to a postgres extension, so anything as an extension would be highly appreciated and helpful

**Comment by apnewberry** [comment]
In case it may be of interest, here is some discussion from Citus on their experience moving to a Postgres extension: ["What it means to be a Postgresql extension"](
https://www.citusdata.com/blog/2017/10/25/what-it-means-to-be-a-postgresql-extension/).

**Comment by merqurio** [comment]
@apnewberry @auvipy would you help in the transition ? Maybe it can be a community driven effort and create a PR. I would more than happy to help in the process.

**Comment by auvipy** [comment]
I have interest to code for this transition, any guideline would be appreciated

**Comment by pratikpparikh** [comment]
@auvipy @merqurio @apnewberry did this take off? if so can you share who has the fork for this repo?

**Comment by auvipy** [comment]
no. I am looking for native support of graph in postgres

**Comment by esatterwhite** [comment]
I would also like to express a desire to see this as an extension. This project looks amazing, but it being a fork is pretty much a non-starter.

**Comment by docteurklein** [comment]
pipelinedb decided to implement it as an extension insteead of a fork too: https://www.pipelinedb.com/blog/pipelinedb-0-9-9-one-more-release-until-pipelinedb-is-a-postgresql-extension

I'd love to see agensgraph take the same decision if possible!

**Comment by archenroot** [comment]
@docteurklein - yeah, totally agree, making fork is now wise, although maybe there was some decision maker which is unknown to me. But in that case if something is missing in the postgres extension subsystem api, then agens should have talk to upstream guys to make it compatible for agens integration as extension...

**Comment by houmanb** [comment]
> I would also like to express a desire to see this as an extension. This project looks amazing, but it being a fork is pretty much a non-starter.

We use postgres as the backend in the production of a medium scale, data centric application since 2003 (~ 7 TB raw data). 

During the last couple of years we were looking for a graph database solution to extend and deepen our insight into the dataset, but I hesitate to take the risk and switch to a "new" database, even though it's a fork, and needless to say that duplicating this amount of data (and keep them in sync) is most inconvenient. 

I would love to use AgensGraph as an extension to the current database just like pipelineDB or timescalDB which we have at least in evaluation right now.

**Comment by baronwangr** [comment]
@auvipy hi, do you still have the plan in turning it into an extension? I'm preparing to do so...

**Comment by SylNah** [comment]
Metoo I would prefer Agensgraph to be a Postgresql extension. Seems Bitnine has heard us: they annouced a beta version "early 2020" . Soon then. 

https://bitnine.net/blog-about-bitnine/blog-activities/agensgraph-postgres-vision-2019-review/

**Comment by ndharasz** [comment]
I'm wanting to try out the extension as soon as it reaches beta. In case others stumble upon this, the extension is currently in development: https://github.com/bitnine-oss/agensgraph-ext

**Comment by emotionbug** [comment]
Apache AGE will be.
---
Closes old issues.
