### ISSUE TITLE
How to use AG with Python?

### ISSUE THREAD

**Issue by vnnw** [bitnine-oss/agensgraph#273]
I tried the following code and got an InternalError error:
"InternalError: current transaction is aborted, commands ignored until end of transaction block"

```
import psycopg2
from psycopg2.extras import Json
import agtype
conn = psycopg2.connect("dbname=ag user=ag")
cur = conn.cursor()
cur.execute("create graph p")
```
What should I do to manipulate AG with python?

**Comment by gtyun** [comment]
I tried 'ygt=# python test.py' with your example, and it works properly.
That error message says that some other transaction is working so you cannot execute create query. I guess you have to commit or abort that transaction first. 

And our python driver, agtype is just a prototype which is based on AgensGraph v1.0.
AgensGraph has been updated a lot, but agtype has not yet.
We're planning to update agtype.

Thank you.

**Comment by vnnw** [comment]
@gtyun , thanks for your kind reply! 
I love Python and PostgreSQL, i can't wait to use the new driver and try your powerful toy~

**Comment by merqurio** [comment]
We are using [this](https://github.com/iomedhealth/agensgraph) for development. (It's a agtype hard fork). It's not complete neither 100% tested but we are committed to keep developing it and up to date.

**Comment by gtyun** [comment]
Oh It's amazing. We need to review it.

**Comment by candysmurf** [comment]
@gtyun & @merqurio, any update on this Python drive. Is it fully supported with all functionalities?

**Comment by merqurio** [comment]
Yes it, is, I just updated the regex thought, I still have to update the
readme and I'll push the changes.
I'll ping you here ASAP

**Comment by gtyun** [comment]
The python driver for AgensGraph is available now.
https://github.com/bitnine-oss/agensgraph-python
