### ISSUE TITLE
Go driver for agensgraph

### ISSUE THREAD

**Issue by candysmurf** [bitnine-oss/agensgraph#277]
May I use any Postgres Go(Golang) drive to work with Agensgraph?

**Comment by gtyun** [comment]
I have never used GO language, but I tested it with https://github.com/lib/pq for a while.
cypher CREATE / SET / DELETE works properly, but MATCH and query result scan fails. 
If you import the jsonb package, it seems to work well, but I do not know how to use it.

**Comment by ps23** [comment]
Have started to play with that a bit: https://github.com/ps23/agensgraph-go

**Comment by candysmurf** [comment]
@ps23, I just saw this. It sounds great. Any progress or update? Can we use it reliably? thanks.

**Comment by gtyun** [comment]
https://github.com/bitnine-oss/agensgraph-golang

It's supported now, so close this issue.
