### ISSUE TITLE
Possible Cypher bug "could not determine which collation to use"

### ISSUE THREAD

**Issue by bravius** [bitnine-oss/agensgraph#282]
I can't get a simple update query to work on AgensGraph 1.2, keeps throwing the following error:

> **could not determine which collation to use for lower() function
> HINT:  Use the COLLATE clause to set the collation explicitly.** 
> 

The query just updates a property using the lower() function.  

The following Cypher reproduces the error:

```
CREATE VLABEL IF NOT EXISTS Person;
CREATE (p:Person {name:'Georgie Porgie'});
MATCH (p:Person) SET p.name = to_jsonb(lower(p.name)) RETURN p;
```
But.... if I create a hybrid query using SQL to perform the lower() function, it works just fine:

```
MATCH (p:Person) SET p.name = to_jsonb((SELECT lower(p.name))) RETURN p;
```

Could this be a bug, or am I doing something wrong with Cypher? I have a workaround, using SQL to invoke the function, but that shouldn't be necessary.

**Comment by gtyun** [comment]
@bravius 
Yes it's a bug. Thank you for your report.
We debugged it through commit [c655dfa](https://github.com/bitnine-oss/agensgraph/commit/c655dfa341227fff56803ee1ffee72b5b85deef8)

That commit merged into master and v1.2.0 too.
