### ISSUE TITLE
[question] How use 'like' in 'match-where' clause ?

### ISSUE THREAD

**Issue by yinmingjun** [bitnine-oss/agensgraph#288]
I try to use 'like' in 'match-where' clause, and I got an error of "Error : ERROR:  syntax error at or near "like"".

The cypher I had tested like this:
match (a:label_a)
where a.name like '%mk%'
return a;

How should I do like this?
Or there are another similar way I can try ?

**Comment by gtyun** [comment]
AgensGraph 1.2 supported 'LIKE' clause but 1.3 and master have some changed in cypher grammar. And we missed it while designing. It's a bug and we will fix it. Thank you for your report.

**Comment by yinmingjun** [comment]
@gtyun 
Thanks for you quickly reply! I'll try AgensGraph 1.2 later.

**Comment by johnberzy-bazinga** [comment]
@gtyun Will other postgres functions also be supported within cypher clauses with the upcoming fix? I'm primarily interested in the functions related to dealing with tsvector.

**Comment by gtyun** [comment]
@johnberzy-bazinga We are considering about supporting all postgresql functions within cypher clauses. This may be included in out roadmap.

**Comment by gtyun** [comment]
See #370
