### ISSUE TITLE
Extend syntex in SQL queries

### ISSUE THREAD

**Issue by merqurio** [bitnine-oss/agensgraph#289]
As from the documentation, actually is possible to query:

```SQL
SELECT [column_name]
FROM ({table_name|SQLquery|CYPHERquery})
WHERE [column_name operator value];
```
I would love to be able to query doing

```SQL
SELECT [column_name]
FROM ({table_name|SQLquery|CYPHERquery})
WHERE [column_name operator value]
IN ({SQLquery|CYPHERquery});
```

```SQL
SELECT * 
FROM edge_label
WHERE edge_label.id 
IN (match (a)-[]->(b {id: 424206003}) return a.id);

ERROR:  syntax error at or near "match"
LINE 1: select * from edge_label where edge_label.id in (match (a)-[...
```
I would love to help implementing it, would some one please let me know how this should be tackle ?
Thanks a lot !!

**Comment by todduk** [comment]
Is it possible at all to reference regular SQL tables?
I see a scenario where a property of an edge contains the id for a SQL lookup.
