### ISSUE TITLE
Bidirectional queries are very slow

### ISSUE THREAD

**Issue by merqurio** [bitnine-oss/agensgraph#290]
Bidirectional openCypher queries are very slow. Maybe you're aware of this, I just wanted to let you know. Hope this helps 👍 
```SQL
iomed=# \timing on
Timing is on.
iomed=# match (a {id:  34534534})<-[r]-(b) return COUNT(type(r));
 count
-------
  7629
(1 row)

Time: 866.517 ms
iomed=# match (a {id:  34534534})-[r]->(b) return COUNT(type(r));
 count
-------
   159
(1 row)

Time: 803.619 ms
iomed=# match (a {id:  34534534})-[r]-(b) return COUNT(type(r));
 count
-------
  7788
(1 row)

Time: 265290.916 ms
```

__System:__
```sh
macOS
Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64
```

__AgensGraph:__
`b8e57de - (HEAD -> master, origin/master, origin/HEAD) `

**Comment by dehowef** [comment]
Hey Gabriel,
Thanks for pointing it out. We'll definitely see what we can do to optimize these queries to run faster.
Glad you're giving AgensGraph a try.
