### ISSUE TITLE
Hybrid Query execute ERROR:  syntax error at or near "::"

### ISSUE THREAD

**Issue by pengxiaojun** [bitnine-oss/agensgraph#292]
I just test the hybrid query samples in agensgraph v1.3. refer [http://bitnine.net/wp-content/uploads/2017/06/html5/main.html#hybrid-query)](url)

sample1: 
`SELECT n.name FROM history, (MATCH (n:dev) RETURN n) AS dev
WHERE history.year > n.year::int
ERROR:  missing FROM-clause entry for table "n"
LINE 1: SELECT n.name FROM history, (MATCH (n:dev) RETURN n) AS dev
               ^`
sample2:
`MATCH (n:dev)
WHERE n.year::int < (SELECT year FROM history WHERE event = 'AgensGraph')
RETURN properties(n) AS n
ERROR:  syntax error at or near "::"
LINE 2: WHERE n.year::int < (SELECT year FROM history WHERE event = ...
                    ^`

I modify the cypher to 
`MATCH (n:dev) WHERE n.year < 2016 RETURN properties(n) AS n`

it works fine.
could someone can point out the error reason ?

**Comment by LeeBeomYong** [comment]
Sample1 and sample2 are the query for AgraphGraph 1.2.0.
The following Sample1 and sample2 have been updated for AgensGraph 1.3.0. 
sample1:
`SELECT n->>'name' as name FROM history, (MATCH (n:dev) RETURN n) as dev 
where history.year > (n->>'year')::int; `
sample2:
`MATCH (n:dev)
WHERE n.year < to_jsonb((SELECT year FROM history WHERE event = 'AgensGraph'))
RETURN properties(n) AS n;`

**Comment by kskim70** [comment]
That is old guide.
You can refer this (http://bitnine.net/wp-content/uploads/2017/06/html5/1.3-quick-guide.html)

**Comment by pengxiaojun** [comment]
@LeeBeomYong 
@kskim70 
many thanks, it works for me.
BTW: 
 1. where can get AG developer manual & operation English document  ?
 2. What is maximum edge and vertex in single graph ?

**Comment by gtyun** [comment]
@pengxiaojun 

1. The English manual is not yet available. 

2. 
Maximum edge and vertex in single **label** is 2^48 - 1= 281474976710655
Maximum label in single **graph** is 2^16 - 1 = 65535
This is because of the graph id data structure.
