### ISSUE TITLE
Counting Nodes with No Relationships

### ISSUE THREAD

**Issue by merqurio** [bitnine-oss/agensgraph#296]
```SQL
MATCH (n) 
WHERE NOT (n)-[]->() 
RETURN count(n)

ERROR:  syntax error at or near "->"
LINE 2: WHERE NOT (n)-[]->() 
                        ^
```
The Cypher query above tries match and count nodes with no incoming or outgoing relationships. Is there any other query I can use ? 

Thanks !

**Comment by ps23** [comment]
According to a comment by @gtyun in #256:
`MATCH (a), (b)-[r]-(c) WHERE a != b and a != c RETURN a`

**Comment by kimkw0227** [comment]
@merqurio If you are using AgensGraph v1.3, you can try exists($graph-pattern) function.

agraph=# match (n)
agraph-#  where exists((n)-[]->())
agraph-#  return count(n);

 count
-------
 49102
(1 row)

Cheers

**Comment by merqurio** [comment]
That worked @kimkw0227 , thanks !
