### ISSUE TITLE
What is the most effective way to insert data into Agensgraph?

### ISSUE THREAD

**Issue by buzhidaowenwen** [bitnine-oss/agensgraph#297]
I would like to ask what is the best way for Agensgraph to insert data into the data? When I used the merge approach to insert data, Agensgraph spent a lot of time calculating (It's like the picture below). 
Red covers sensitive information, which can be understood as the content of a vertex name, And a unique index was created on vertex's property name.

![image](https://user-images.githubusercontent.com/11647791/34930093-b80698ae-fa02-11e7-9fa0-d167a42b818a.png)

**Comment by gtyun** [comment]
MERGE always check vertices and edges duplication before insert. So it can be slower than CREATE.
If you can ensure that there is no duplicated data source or no matter with data duplication, than use CREATE.

**Comment by buzhidaowenwen** [comment]
If so, then my business might be better suited to using the merge.The data that I'm inserting now, all of them are PreparedStatement and then sent to the server.The performance is good by looking at pg_log.

**Comment by buzhidaowenwen** [comment]
But I use the merge operation, why does the unique index conflict? Is it because of the merge of the same data?
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "idx_mobile_name"

**Comment by buzhidaowenwen** [comment]
When my database has nearly 100 million vertex, using the merge, the speed drops will be particularly fast.And the machines (8 cores, 16 gigabytes of memory) have a particularly high load, with 15.5 gigabytes of memory, load balance 10.5.

**Comment by gtyun** [comment]
I think the two nodes are not exactly the same, but they have the same key and value. So that unique index conflict occurs.

**Comment by buzhidaowenwen** [comment]
Can you help me with the other questions? When the amount of data is 100 million points, the insertion speed drops very quickly.

**Comment by gtyun** [comment]
1. I have no advice now.
2. How did you count record of table? 
If your query was in this way,

`SELECT count(*) FROM agensgraph.ag_vertex ;`

This query get all record of ag_vertex and it's child tables too. 
So that records are not inserted into ag_vertex but selected together.
If you want to count record of one table with out its children, you can use keyword ONLY like this way.

`SELECT count(*) FROM ONLY agensgraph.ag_vertex ;`
