### ISSUE TITLE
Agensgraph  throw org.postgresql.util.PSQLException: FATAL: the database system is in recovery mode

### ISSUE THREAD

**Issue by buzhidaowenwen** [bitnine-oss/agensgraph#298]
When I use the driver to connect to agensgraph, the service side reports recovery mode exception.
org.postgresql.util.PSQLException: FATAL: the database system is in recovery mode.

![image](https://user-images.githubusercontent.com/11647791/34976279-d1a0ff2e-fad0-11e7-86d9-5bd4b3e48074.png)

**Comment by gtyun** [comment]
Can you connect with prompt (agens or psql) ? Same exception has occured?
And what kind of driver is used for connect? JDBC or others?
Please provide some more information.

**Comment by buzhidaowenwen** [comment]
I'm using a JDBC connection. When this error occurs, I cannot connect to the database through agens.

**Comment by buzhidaowenwen** [comment]
Machine configuration is CPU 8 core, memory 16GB.
When I do not use the connection pool and adjust the shared_buffers from 8GB to 4GB, no recovery mode Exception is reported. I use the knowledge in the quick start guide to operate.
During the period, I also used the direct JDBC connection (not using the connection pool), and I tested with shared_buffers 8G and still reported recovery mode exception. 
And I see that postgresql's website has a different configuration for shared_buffers than Agensgraph does.

Agensgraph:
![image](https://user-images.githubusercontent.com/11647791/35023379-5151b05c-fb75-11e7-921c-ff2da5fc2bd0.png)

Postgresql:
![image](https://user-images.githubusercontent.com/11647791/35023436-9c9484ea-fb75-11e7-8279-220a1a2bb9e0.png)

**Comment by buzhidaowenwen** [comment]
Can you provide a demo that connects Agengraph?A better performance approach.

**Comment by buzhidaowenwen** [comment]
@gtyun @dehowef 
Java applications access Agensgraph, can I use the connection pool?Because when I use connection pool access, the recovery mode Exception is reported for a period of time.Using JDBC directly, however, does not have this problem.

**Comment by buzhidaowenwen** [comment]
@gtyun 
If you have time, help with this problem.

**Comment by gtyun** [comment]
Current Agensgraph JDBC driver does not support connection pooling. We are fixing.

**Comment by buzhidaowenwen** [comment]
Thank you for your reply.Looking forward to your good news.
