### ISSUE TITLE
Set default `graph_path`

### ISSUE THREAD

**Issue by merqurio** [bitnine-oss/agensgraph#300]
Is there a way to set a default `graph_path` as a fallback if there is no graph_path set ? 

Thanks !

**Comment by merqurio** [comment]
It would be interesting to add a `FROM` to the match queries to set the `graph_path`. For example:

```sql
MATCH (a {active: 1})-[r]->(b {id: 28320003, active: 1}) FROM my_graph_path RETURN DISTINCT a.id
```

**Comment by gtyun** [comment]
You can set default graph_path (or other postgresql user configure variables) with ALTER DATABASE/USER command like this way,
`ALTER USER ygt SET graph_path = 'sample'`

Your suggestion is interesting. 
If that query has enabled, one query can search multi graph at once. And we discussed whether such a query is necessary or not.
We decided that if some query need to search between graphs, that graphs should be one graph from scratch.

Of course we can be wrong and ready to hear the suggestions.

Thanks !

**Comment by merqurio** [comment]
Thanks for the tip @gtyun !

In our case, we have two graph and multiple tables. One of the graph is used to ease a SQL query and this graph is _immutable_. 

The second graph is used to store metadata about rows (multiple hierarchies). This one is mutable and can be modified on creation/edit/deletion.

This is why this kind of syntax could be interesting for us to get to the intersection of both graphs, but we do understand this can be difficult to implement
