### ISSUE TITLE
Why does Agengraph's create operation require 8ms?

### ISSUE THREAD

**Issue by buzhidaowenwen** [bitnine-oss/agensgraph#301]
On the Agensgraph server, I used the agens command to enter the database of Agensgraph.The create operation is performed directly, and the single strip requires more than 8ms, while the insert of pg itself is much less time-consuming.Is it because of the primary key id?

![image](https://user-images.githubusercontent.com/11647791/35182194-d06445b6-fe0a-11e7-80ef-7315f2d10b68.png)

**Comment by buzhidaowenwen** [comment]
@gtyun The figure above is where I perform the create operation directly on the command line. Can you help me figure out where the problem is?

**Comment by gtyun** [comment]
We did a test and found no significant difference between them, postgresql insert and agensgraph create. Other factors may have affected the experimental results.
