### ISSUE TITLE
Performance of large amount data

### ISSUE THREAD

**Issue by dingzeshuan** [bitnine-oss/agensgraph#306]
Dear AgensGraph team:
I wonder how many vertices and relationships do the Agens  supports, without considering the hardware limit.
If I store billions vertices and 100 billions relationships using AgensGraph, Is there will be bad performance?

Longing for your  comment.

**Comment by gtyun** [comment]
The performance depends on the graph configuration, so it's hard to talk about it.
Users can physically generate 2 ^ 16 labels, and a label can store 2 ^ 48 graph elements(vertexes or edges).
