### ISSUE TITLE
Does Agensgraph work for Stolon as HA?

### ISSUE THREAD

**Issue by candysmurf** [bitnine-oss/agensgraph#313]
May I know if Agensgraph would work with Stolon to support High Availability?
Stolon is at this repo: https://github.com/sorintlab/stolon

**Comment by gtyun** [comment]
We have used pacemaker for HA cluster, no experience with Stolon. Looking at the link, it seems possible that Agensgraph could work with Stolon but requires review and demonstration. I will consider adding this work to the schedule.

**Comment by gtyun** [comment]
AgensGraph is working with Stolon.
We created cluster using Stolon and tested to see if fail-over and fail-back are working as they are supposed to.

**Comment by zzl221000** [comment]
@gtyun 
Where can I find a tutorial on deploying agens using a stolon cluster?

**Comment by joefagan** [comment]
https://hub.docker.com/r/bitnine/stolon/
