### ISSUE TITLE
How does Agensgraph edge 3 billion + query performance optimize?

### ISSUE THREAD

**Issue by buzhidaowenwen** [bitnine-oss/agensgraph#316]
HI, @gtyun 
I have to trouble you again,  My question is as follows:

**Machine configuration**: 24 core, 128gb memory, 3T SSD hard disk, master-slave architecture.
**Data volume**: 900 million, 3.3 billion.
**Execution** :Execution of the following statement, through the execution plan, is the full index.But it can take hundreds of milliseconds or even seconds, if the data is not hit in the cache.

Query time consuming:
![image](https://user-images.githubusercontent.com/11647791/36723236-aa9cc580-1bea-11e8-82c3-6ab0dc932e45.png)
Query time consuming:
![image](https://user-images.githubusercontent.com/11647791/36723246-b0c46eae-1bea-11e8-9766-15271c9df39e.png),
 execution plan:
![image](https://user-images.githubusercontent.com/11647791/36723300-d4f3ff4c-1bea-11e8-9e98-5167d3702f30.png)

**Comment by gtyun** [comment]
Bidirectional queries are generally slower than unidirectional queries. As you can see, bidirectional query must search both start index and end index. 
And if you know that 'd' has label 'device' before query, set label name on match query.
Based on the above results, the recommended query is as follows.
`MATCH (n:MOBILE {name:'xxxxx'})<-[r]-(d:DEVICE) RETURN d;`

**Comment by buzhidaowenwen** [comment]
@gtyun 
Thank you for your reply.
Yes, it can be faster with the direction of the query, which is already used in our production.I would like to ask if there are other optimization directions, such as configuration tuning, machine memory adjustment, etc.

**Comment by gtyun** [comment]
Oh, that query had a reason to do so. 
Hmm.. we sometimes adjust 'random_page_cost' to get better plan, but above plan is perfect. IOS (index only scan) is the fastest way to scan records in postgresql. 
I'm sorry for I can't help you. You can reference other postgresql server configuration.

**Comment by buzhidaowenwen** [comment]
Thanks for your help. 
Other aspects of the tuning plan, I also made some common sense, the effect is not ideal. Would it be better if I added 128gb of memory? Because of the amount of data, it's going to be 10 billion.

**Comment by gtyun** [comment]
It will be depend on your indexes size. If every indexes already cached in 128gb memory, additional memory can not bring dramatic results.

**Comment by gtyun** [comment]
Size of database could be important. What is the database size with 3.3 billion elements graph? Maybe it is possible that all database be cached in memory.

**Comment by buzhidaowenwen** [comment]
I now have 900 million, 3.3 billion edges.The total index file size is 300G+.  In this case, increasing memory will help.
