### ISSUE TITLE
Graph Data Import

### ISSUE THREAD

**Issue by opamyouk** [bitnine-oss/agensgraph#321]
Hi guys,

i try to load data from csv file, but i want to use Merge.

hear is my file :

head Mail_0.csv
idPivots,Date,LABEL_pivots,idIdentification_source,nameIdentification_source,uuidSource,idPropagation,LABEL_Identification_source,idNIR,nameNIR,nir,LABEL_NIR
0007608,2018/2/20,Pivots,0007589,Identification_source,P9RTC7T8,69363IDA,Identification_source,0007597,NIR,1234567891111,NIR
0007631,2018/2/20,Pivots,0007612,Identification_source,A4SBFIOD,OE23HEFC,Identification_source,0007620,NIR,1234567891461,NIR

I try this syntax : 

LOAD FROM Relation_Relation_Mail AS kp
CREATE (pivots:Pivots {idPivots: to_jsonb(kp).idPivots,Date: to_jsonb(kp).Date})
MERGE (identification_source:identification_source {idIdentification_source: to_jsonb(kp).idIdentification_source,name: to_jsonb(kp).nameIdentification_source,uuidSource: to_jsonb(kp).uuidSource,idPropagation: to_jsonb(kp).idPropagation})
MERGE (nir:nir {idNIR: to_jsonb(kp).idNIR,name: to_jsonb(kp).nameNIR,nir: to_jsonb(kp).nir})
CREATE (pivots)-[:Mail]->(identification_source)
CREATE (pivots)-[:Mail]-> (nir);

My database has  1 Million vertex and 2,5 Million Edge.

Should i disable indexes before loading extra data ?
When i used MERGE syntax, insert hang.

For exemple , this works 

dbbagep00d=# LOAD FROM Relation_Mail AS kp
dbbagep00d-# CREATE (pivots:Pivots {idPivots: to_jsonb(kp).idPivots,Date: to_jsonb(kp).Date})
dbbagep00d-# ;
GRAPH WRITE (INSERT VERTEX 190001, INSERT EDGE 0)
 
Thanks for your help.

Regards
Vincent

**Comment by gtyun** [comment]
Hi @opamyouk ,

'Disable index(and reindex)' is good way for CREATE but not for MERGE.
So if you want to use it, you need to divide labels to disable index or not.

The labels for MERGE are looks like identification_source and nir, right?
MERGE checks all of the property. If every properties are almost same but just one diff, MERGE must create a new node. I guess that your MERGE query is checking too many properties. (And that properties have index? or not?) 
If there is any unique property then create unique index on the key, simplify MERGE query with the key and use SET for the other properties. It would be better.

Try it and message me if there is more problem.
Thanks.

**Comment by opamyouk** [comment]
Hi @gtyun ,

thanks, i will check and tell you as soon as i will be able to check this.

Regards,
Vincent

**Comment by opamyouk** [comment]
Hi,
i succeed doing the import.
I used 2 loop to do so.

1) insert new Pivots
2) check with match for edge creation for both (nir and identification_source)

i only used the key for the match clause.

TY.

Regards,
Vincent
