### ISSUE TITLE
return node if relationship is not present.

### ISSUE THREAD

**Issue by opamyouk** [bitnine-oss/agensgraph#322]
Hi,

another query 
- i want to return node if relationship is not present.

Is this possible ?

Regards,
Vincent

**Comment by gtyun** [comment]
You can reference #296 
`MATCH (a), (b)-[r]-(c) WHERE a != b and a != c RETURN a;`
or
`match (n) where not exists((n)-[]->()) return count(n);`

**Comment by opamyouk** [comment]
Hi guys, 

thank you for the response. Sorry, i missed the #296.

It works.
