### ISSUE TITLE
Why does this query scan the tables that you don't need?

### ISSUE THREAD

**Issue by buzhidaowenwen** [bitnine-oss/agensgraph#323]
@gtyun 
Why does this query scan the tables that you don't need?

explain (analyze,verbose,buffers,costs) match (fromNode:MOBILE)-[use]->(device:DEVICE)-[has]->(toNode:MOBILE) where  fromNode.name  = '******' return toNode;

![image](https://user-images.githubusercontent.com/11647791/37265018-b3875128-25eb-11e8-8d2a-5c38af37207f.png)

**Comment by gtyun** [comment]
'use' and 'has' are not assigned to label, so Agensgraph had to search all kind of edge labels.

**Comment by gtyun** [comment]
If so, use '[:use]' and '[:has]' instead of [use], [has] in the match query. It's just variable without colon(':'), not label name.

**Comment by buzhidaowenwen** [comment]
This place is not exactly the same as when I used neo4j.After the adjustment you said, the speed will be faster.

Thank you for your patience.

**Comment by buzhidaowenwen** [comment]
Please pay attention to this question(#324). When I use the in keyword, Agensgraph will use seq scan.
