### ISSUE TITLE
Role based Access Control

### ISSUE THREAD

**Issue by candysmurf** [bitnine-oss/agensgraph#325]
Does Agensgraph support role-based access control? If it does, do you have a doc for it?

**Comment by gtyun** [comment]
English manual is not prepared yet. But you can reference postgresql doc. https://www.postgresql.org/docs/9.6/static/role-membership.html 

The most of the feature is same but there is one different thing. If a role want to create label, it should inherit the role which created the graph. Because of Agensgraph structure.

**Comment by candysmurf** [comment]
thanks @gtyun, I'll read that.

**Comment by candysmurf** [comment]
Hey, can agensgraph work with [stolon](https://github.com/sorintlab/stolon)?

**Comment by gtyun** [comment]
Yes, it works well. One of us tested stolon with etcd and kubernetis.

**Comment by candysmurf** [comment]
@gtyun, which image did you use? I tried kimkw0227/agensgraph-docker didn't work. Anything special do I need to do besides the image?

**Comment by joshuayb** [comment]
Hi Emily,

Please, refer to the Github page.
[https://github.com/bitnineQA/agensgraph-docker/tree/master/kubernetes](https://github.com/bitnineQA/agensgraph-docker/tree/master/kubernetes)

README.md contains the instruction to form and execute Stolon + Kubernetes.
Bin folder contains Stolon binary, Stolon folder has Kubernetes which creates Stolon files.

Please, let us know if works for you.

**Comment by candysmurf** [comment]
@joshuayb , thanks. let me give it a try and will let you know. I'm going to run it on my mac osx.

**Comment by candysmurf** [comment]
@joshuayb , the binary under bin does not work on Mac OSX. Do I have to run it on centos7.x? I was able to run stolon on Mac for postgresSQL.

**Comment by candysmurf** [comment]
@joshuayb, your image works well with stolon. I just tested it. thank you very much for your help.
Thanks to you both, @gtyun as well. Appreciate your timely help!
