### ISSUE TITLE
Aggregate function does not work after upgrading to 1.3

### ISSUE THREAD

**Issue by bravius** [bitnine-oss/agensgraph#333]
After upgrading from AgensGraph 1.2 to 1.3, this query containing aggregate functions no longer works:

`MATCH (n:vEncounter) RETURN {min:min(n.date), max:max(n.date)} as date, json_agg(DISTINCT n.location ORDER BY n.location) as location`

Where this worked before in 1.2, I now get "syntax error at or near "ORDER" with 1.3

If I remove the ORDER BY clause:

`MATCH (n:vEncounter) RETURN {min:min(n.date), max:max(n.date)} as date, json_agg(DISTINCT n.location) as location`

Then I get "error: aggregate must exist solely".

If I simplify further:

`MATCH (n:vEncounter) RETURN json_agg(DISTINCT n.location) as location`

The query succeeds, but I have had to take out the aggregate sub-clause `ORDER BY` and have lost sorting.

It also does not matter if I use json_agg or array_agg, the result is the same.

Seems to me something has broken with parsing aggregate expressions in 1.3, as the original query should be valid syntax, and worked in 1,2.

EDIT:

After rewriting the query to this:

`MATCH (n:vEncounter) 
WITH n ORDER BY n.location 
WITH min(n.date) as mn, max(n.date) as mx, collect(DISTINCT n.location) as location
RETURN {min:mn, max:mx} as date, location`

It will now return the same structure of the original query (which worked in 1.2).

However, now the ORDER BY clause does not recognize DESC and location will not sort in descending order.

**Comment by emotionbug** [comment]
Closes old issues.
