### ISSUE TITLE
Short Guide link is broken

### ISSUE THREAD

**Issue by candysmurf** [bitnine-oss/agensgraph#334]
when you click the short guide link, it showed page not found.

**Comment by joshuayb** [comment]
Hi Emily,

Would you try the link again?

http://bitnine.net/documentations/quick-guide-1-3.html

Whether it works or not, I have the Developer Manual, which will be uploaded to the Documentation page next week. Please, give me your e-mail address at joshua@bitnine.net. I will send the full manual for you.

Thank you.
