### ISSUE TITLE
There is a problem with the edge set properties

### ISSUE THREAD

**Issue by wenxue202012** [bitnine-oss/agensgraph#335]
When I set properties to the side, I use the following statement, which is particularly slow.The main time is on the graph_set.

match (f:mobile{name:'***'}) match(t:mobile{name:'***'}) match(f)-[r:call]->(t) set r.mgm=1;

![image](https://user-images.githubusercontent.com/11647791/37764626-21f905d4-2dfd-11e8-8bc8-a54d13295b25.png)

**Comment by buzhidaowenwen** [comment]
@gtyun 
This problem is met by my production environment, which has a great impact on my system. I hope you can help with it. Thank you!

**Comment by buzhidaowenwen** [comment]
match (f1:mobile{name:'***'})-[r1:call]->(t1:mobile{name:'***'}) where  delete(r1);
it has the same problem.

**Comment by gtyun** [comment]
This is same with #319 .
It will resolved via #312

**Comment by emotionbug** [comment]
Closes old issues.
