### ISSUE TITLE
Long attribute in Json

### ISSUE THREAD

**Issue by traxtech** [bitnine-oss/agensgraph#340]
Hi.

Storing long numbers in Json attributes does not work correctly.

CREATE VLABEL testlong;
CREATE(a:testlong {id: 6384388842048196616 });
MATCH (a:testlong) return a.id;
DROP VLABEL testlong;

ECMA 262 only requires a precision of 21 bits in Json, but .. maybe you could support the full precision ? (stroring the attribute as text seems a weak alternative to me)

Thanxs.

**Comment by johnberzy-bazinga** [comment]
@traxtech Are you using PGAdmin or some other browser-based administration tool by any chance? I'm pretty certain the value is loosing precision due to the browser as `jsonb` (the backing type for vertex/edge properties) can store longs without any issues.

**Comment by traxtech** [comment]
The error occured while using the jdbc driver and the bitnine JSON api (net.bitnine:agensgraph-jdbc:1.4.2) and I also got it while using AgensBrowser Web.

**Comment by johnberzy-bazinga** [comment]
The driver should work fine. It's most likely an issue with client-side JS loosing precision.

**Comment by traxtech** [comment]
So, a bug on AgensGraph Web but not on the graph db. Thanks.
