### ISSUE TITLE
Create a node with multiple labels

### ISSUE THREAD

**Issue by jgranduel** [bitnine-oss/agensgraph#343]
Hi, 

I've just discovered AgensGraph (v1.3.1) and trying to see what parts of OpenCypher are implemented as of today.
I've followed [Neo4J](https://neo4j.com/docs/developer-manual/current/cypher/clauses/create/#create-create-a-node-with-a-label) doc, and cannot create a node with more than one label:
```
graph =# create (n:A:B);
ERROR:  syntax error at or near ":"
LINE 1: create (n:A:B);
```
Is it on the roadmap and BTW? and is there a conformance table  (as [luizperes'one](https://gist.github.com/luizperes/ad88812025befb0732be7f59d4124dc9#list-of-statements-not-all-included)).
Thanks a lot

**Comment by gtyun** [comment]
AgensGraph does not support multiple labels. Instead, we provide label inheritance. 
You can reference this document. http://bitnine.net/documentations/quick-guide-1-3.html

**Comment by jgranduel** [comment]
Thank you very much.
I had indeed seend inherits in the Quick Guide, but does it mean you won't ever support it (just for cypher conformance).

**Comment by gtyun** [comment]
No we won’t. Because of internal structure.  And we think that multi label can be covered with inheritance. Of course the graph model should be fixed a little.

**Comment by jgranduel** [comment]
thanks a lot;
