### ISSUE TITLE
Does it scale? (Question for contributors)

### ISSUE THREAD

**Issue by Extarys** [bitnine-oss/agensgraph#361]
Well, this is and is not an actual issue. I think the best place to get the best answers are near the contributors :smile: .

How can I scale AgensGraph? Or when will it be possible? I searched with 3 websites and only find code reference or articles about AgensGraph.
 
I was planning on using PostgreSQL but since it's hard to scale I switched my data to CockroachDB. But a graph database would make my life much easier - if it scales.

I'd prefer an open source version and if I make money, sponsor it than paying 5K+ to a database that use RQL (Random query language).

Thanks for your time.

**Comment by gtyun** [comment]
If the 'scale' means 'scale-out' (like sharding), agensgraph does not support it.
Replication is possible but I'm not sure this is what you want.

**Comment by Extarys** [comment]
Aww I see, I knew it wasn't a dream come true :P Tanks!

**Comment by merqurio** [comment]
@Extarys Depending on how you're storing your data, check [citus](https://www.citusdata.com/) it might help you to scale out  ?
