### ISSUE TITLE
Order By Clause following a With Clause is not respected

### ISSUE THREAD

**Issue by johnberzy-bazinga** [bitnine-oss/agensgraph#362]
Agens does not seem to respect the order by clause following a with clause when nodes projected in that with are subsequently used in a match.

*Repro*
```
CREATE VLABEL time;
CREATE ELABEL goes;

CREATE (:time {sec: 1})-[:goes]->
       (:time {sec: 2})-[:goes]->
       (:time {sec: 3})-[:goes]->
       (:time {sec: 4})-[:goes]->
       (:time {sec: 5})-[:goes]->
       (:time {sec: 6})-[:goes]->
       (:time {sec: 7})-[:goes]->
       (:time {sec: 8})-[:goes]->
       (:time {sec: 9});

match (a:time)
with a
order by a.sec desc
match (a)-[:goes]->(b)
return a
```

*RESULT*
```
"time[3.1]{"sec": 1}"
"time[3.2]{"sec": 2}"
"time[3.3]{"sec": 3}"
"time[3.4]{"sec": 4}"
"time[3.5]{"sec": 5}"
"time[3.6]{"sec": 6}"
"time[3.7]{"sec": 7}"
"time[3.8]{"sec": 8}"
```

When excluding `a` from the final match, the results are returned in the correct order:

```
match (a:time)
with a.sec as s, a
order by s desc
return a
```
Thanks,
John

**Comment by gtyun** [comment]
Hello, John

In that case, WITH clause sorted the results, but MATCH sort again to find graph pattern.
You can see it through LIMIT / SKIP clause.

`match (a:time)
with a
order by a.sec desc limit 4
match (a)-[:goes]->(b)
return a ;
`

**Comment by johnberzy-bazinga** [comment]
@gtyun Thanks for the clarification. I'll close this as it's by design.

Thanks
