### ISSUE TITLE
How can I create an edge with existing vertexes?

### ISSUE THREAD

**Issue by amosbird** [bitnine-oss/agensgraph#365]
Hi, when creating edges via `create (:x {name: 1})-[:e {name: 1}]->(:x {name: 2})`, agensgraph always inserts two new vertexes. Is there a way to avoid that?

**Comment by gtyun** [comment]
You can do it with following query,

`MATCH (a:x {name: 1}), (b:x {name:2})
CREATE (a)-[:e {name: 1}]->(b)`

**Comment by amosbird** [comment]
Ah, thanks!
