### ISSUE TITLE
Get all paths of a graph - Does Agensgraph support unwind (ERROR: syntax error at or near "unwind)

### ISSUE THREAD

**Issue by pratikpparikh** [bitnine-oss/agensgraph#368]
Dear author,
   
What is the best way to get all paths of graph in agensgraph.  I tried to follow an example from stackoverflow for neo4j, can you help or provide direction to achieve the same described in https://stackoverflow.com/questions/39649774/get-all-paths-neo4j-cypher.   I also found the following query should work but rather provides me an error.

match (a {name:"Daniel"}), (b {name:"Jerry"})
with a,b
match s = shortestPath(a-[]-b)
unwind nodes(s) as n
return n.name as Names

[2018-05-24 07:26:58] [42601] ERROR: syntax error at or near "unwind"
[2018-05-24 07:26:58] Position: 68

Regards,
Pratik Parikh

**Comment by gtyun** [comment]
For now `UNWIND` is not supported. We are developing it.
You can try it with `jsonb_array_elements()`. It becomes more complicated query, can not help it now..

`select jsonb_array_elements(gdb_tb.nodes)`
`from (`
`match (a {name:'daniel'}), (b {name:'Jerry'})`
`with a,b`
`match s = shortestPath((a)-[*]-(b))`
`return to_jsonb(nodes(s)) as nodes) gdb_tb;`

**Comment by pratikpparikh** [comment]
@gtyun Thank you.

**Comment by gtyun** [comment]
You are welcome.
