### ISSUE TITLE
[question] How use 'like' clause ? 

### ISSUE THREAD

**Issue by akshaybahadur21** [bitnine-oss/agensgraph#370]
I try to use 'like' in 'match-where' clause, and I got an error of "Error : ERROR: syntax error at or near "like"".

The cypher I had tested like this:
match (a) where a.name like '%mk%' return a;

How should I do like this?
Or there are another similar way I can try ?

**Comment by gtyun** [comment]
For the sample, you can use `CONTAINS` clause.
`MATCH (a) WHERE a.name CONTAINS 'mk' RETURN a`

There is `START WITH` , `END WITH` clauses also.
If you want to use more complicated pattern matching, regular expression can be used with `=~` .

**Comment by gtyun** [comment]
This feature will be available in the next release.

**Comment by akshaybahadur21** [comment]
Cant reproduce the same in 1.3.1 or 1.3 version for agensGraph.
Which version are you using?

**Comment by gtyun** [comment]
It is developing version. This feature is committed after 1.3.1 release.

**Comment by akshaybahadur21** [comment]
So when will you be releasing the next version?

**Comment by gtyun** [comment]
It is scheduled for ealry July.

**Comment by akshaybahadur21** [comment]
So is there any alternative or a quickfix for users who are using 1.3 or 1.3.1

**Comment by johnberzy-bazinga** [comment]
This below hack seems to work, but I have not checked the performance impact:

```
match (m:movie) 
where like(text(m.title), text('Foo%'))
return m
```

**Comment by akshaybahadur21** [comment]
Got it.
Thanks.
All the best for the next release.
