### ISSUE TITLE
Binary format support for data in/out for Agens Data Types.

### ISSUE THREAD

**Issue by pratikpparikh** [bitnine-oss/agensgraph#379]
Dear Authors,
     
I am facing a problem whereby when querying a simple query "match (n:category {'name':'home'}) return n;", the result return in binary format is not usable as it returns garbage values for label and gid. Below is the example of  actual results and expected result
Actual 
     Z           ?   s{"id": "cf0cee84-68ea-11e8-aa02-ff2396de2b3b", "name": "home", "creationDate": "2018-06-05T18:03:52.857729+00:00"}           
  
Expected 
category[3.1]{"id": "42e14dcc-68ec-11e8-aa9b-2bb4496c4403", "name": "home", "creationDate": "2018-06-05T18:14:17.064237+00:00"}

@johnberzy-bazinga, @mlogue, @kskim80  and @protodef can you please help get this addressed, as you all looked at this as part of #115.  Really appreciate your help in the matter.

I can't use encode function as it does not accept vertex, plus I think we (Agens Engine) should have support for binary formats as will help in perfomance.

Regards,
Pratik Parikh

**Comment by johnberzy-bazinga** [comment]
@pratikpparikh 
What driver are you using? I'm using the binary format just fine, but you need to have a handler in the driver take care of the graphid type. The Vertex, Edge and Graphpath types are composite types, so in general, the driver should be able to read/write them fine.

**Comment by johnberzy-bazinga** [comment]
@pratikpparikh I noticed your PR but was a bit confused about if it's necessary. I'm by no means that experienced with the internals of postgres, but my understanding is the record_* functions are enough to support the binary encoding of the vertex/edge/graphpath types as they're just composites of existing types that already have binary representation (specifically, graphid and jsonb).  I'm currently using the binary encoding in npgsql and all I had to do was implement the [graphid handler](https://github.com/johnberzy-bazinga/Npgsql.AgensGraph/blob/master/src/Npgsql.AgensGraph/GraphIdHandler.cs) (note: there is an additional tid field in the 2.0 branch for edge and vertex types). 

Maybe the devs at bitnine can shed more light, but I'm almost certain all that's required is writing some sort of handler for graphid and the composite types should come OOB with most drivers (maybe with some mapping).

Regards,
John

**Comment by pratikpparikh** [comment]
@johnberzy-bazinga It is for sure necessary.  A pure native driver with binary format support won't deserialize vertex, edge, and graphpath.  The build I working now and I have my driver work working perfectly as well.

Regards,
Pratik Parikh

**Comment by johnberzy-bazinga** [comment]
@pratikpparikh The vertex/edge/graphpath composite types end up being handled by the [composite handler](https://github.com/npgsql/npgsql/blob/master/src/Npgsql/TypeHandlers/UnmappedCompositeHandler.cs). which delegates to either the graphid handler I wrote or the built-in jsonb handler. None of it falls back to the text-based encoding.

**Comment by pratikpparikh** [comment]
@johnberzy-bazinga what I found is that it does not work the way you have described.  Without having specific (vertex/edge/graphpath)_send handlers I was getting bad content back emitted by  (vertex/edge/graphpath)_out handler which was in text format and not converted back to binary byte stream.  What is the best way to test the theory of delegation to graphid or in build jsonb handler?  The main problem was not label, graphid emitted with garbage value as shown below, this was not addressed until I implemented the send methods for all three data types.  Do you have unit testing around this functionality? 

Actual
� �Z � � � �? s�{"id": "cf0cee84-68ea-11e8-aa02-ff2396de2b3b", "name": "home", "creationDate": "2018-06-05T18:03:52.857729+00:00"} � � �

Expected
category[3.1]{"id": "42e14dcc-68ec-11e8-aa9b-2bb4496c4403", "name": "home", "creationDate": "2018-06-05T18:14:17.064237+00:00"}

**Comment by johnberzy-bazinga** [comment]
@pratikpparikh Since the above mentioned types are generic row/composite types they don't need any special encoding. The driver should already understand the structure and should be able to send/recv them generically. In Npgsql you map composites via `conn.TypeMapper.MapComposite<SomeType>("some_composite")` and as long as the constituent fields have a handler it is able to [delegate to those handlers](https://github.com/npgsql/npgsql/blob/dev/src/Npgsql/TypeHandlers/UnmappedCompositeHandler.cs#L129-L141). Out of curiosity, what driver are you using? Does it have the facility to map a composite type? 

Also, if you look at the [pg_type](https://github.com/bitnine-oss/agensgraph/blob/ef1b4c177eb458ce65a9eb77cf5ca4a3ef8c049c/src/include/catalog/pg_type.h#L63 ) mapping you'll see the graphid mapped to 'b' (base type) while the rest of the graph types are mapped to 'c' (composite).

**Comment by johnberzy-bazinga** [comment]
If you'd like to test with npgsql you can try running the test below.

note: If you're building agens from source, you'll also need to add a new field `public NpgsqlTid Tid {get; set;}` to the [vertex/edge](https://github.com/johnberzy-bazinga/Npgsql.AgensGraph/blob/master/src/Npgsql.AgensGraph/AgensGraphTypes.cs#L39-L51) types.


https://github.com/johnberzy-bazinga/Npgsql.AgensGraph/blob/tests/Npgsql.AgensGraph.Tests/ConnectionTests.cs
