### ISSUE TITLE
max_parallel_workers_per_gather don't work in agengraph 13.1

### ISSUE THREAD

**Issue by imsagraph** [bitnine-oss/agensgraph#381]
Hi, i am trying use parameter max_parallel_workers_per_gather but i have an error
max_parallel_workers_per_gather = 4     # taken from max_worker_processes

MATCH (dossier:Dossier{DossierAT:''})-[:TRCF]->(:Pivots)-[:IFTR]-(dsn:IdDSN)-[r:IFTR]-(n:Pivots)<-[:STATUS]-(:Status_Pivot{name:'OK'}) with n match (n)<-[:TRCF]-(crm:IdCRM) return crm;
ERROR:  failed to initialize graph_path to ""
CONTEXT:  parallel worker

Have you some workaround ?

Regards

**Comment by gtyun** [comment]
Hi, 
How did you set the graph_path ? Have you used 'ALTER ROLE or DATABASE' ?
If so, please try with 'set graph_path' for the session.

**Comment by imsagraph** [comment]
Hi,
graph_path is set :
2018-06-08 13:03:51 CEST [12895]: [32-1] LOG:  received SIGHUP, reloading configuration files
2018-06-08 13:03:51 CEST [12895]: [33-1] LOG:  parameter "max_parallel_workers_per_gather" changed to "4"
agens (AgensGraph 1.3.0, based on PostgreSQL 9.6.2)
Type "help" for help.

dbbagep00d=# show graph_path;
 graph_path
------------
 sgraphpoc
(1 row)

dbbagep00d=# MATCH (dossierAt:DossierAT{DossierAT:'VMUTEO8L'})-[:TRCF]->(:Pivots)-[:IFTR]-(dsn:IdDSN)-[r:IFTR]-(n:Pivots)<-[:STATUS]-(:Status_Pivot{name:'OK'}) with n match (n)<-[:TRCF]-(crm:IdCRM) return crm;
ERROR:  failed to initialize graph_path to ""
CONTEXT:  parallel worker

**Comment by imsagraph** [comment]
Hi,
my graph path is on database 
ALTER DATABASE DATABASE_nom SET graph_path=sgraphpoc;

Do you have workaround for version 1.3.1 ?
How migrate in the next release  (pg_dump) ? 

regards

**Comment by gtyun** [comment]
The workaround is.. do not use `ALTER DATABASE .. SET graph_path`. And use `SET graph_path` for every new session.

**Comment by imsagraph** [comment]
Thanks for workaround, now it's ok. We don't asign graph_path at database, user...
When next release is coming please ?

**Comment by gtyun** [comment]
It's planned to July.

**Comment by imsagraph** [comment]
Thanks
