### ISSUE TITLE
Import data according to Quick Guide get a error

### ISSUE THREAD

**Issue by zzl221000** [bitnine-oss/agensgraph#388]
agens=# LOAD FROM testt AS profile_name CREATE (a:test_vlabel = row_to_json(profile_name)::jsonb);
ERROR:  syntax error at or near "::"
LINE 1: ...me CREATE (a:test_vlabel = row_to_json(profile_name)::jsonb);

agensgraph for windows

**Comment by bylee5** [comment]
:: is not allowed.

Please try the following:
LOAD FROM testt AS profile_name 
CREATE (a:test_vlabel = to_jsonb(row_to_json(profile_name)));

**Comment by zzl221000** [comment]
@bylee5 Thank you!  but when I use to_jsonb will cause double quotes to become escape string, my foreign table data is already a json format string, how to let it stop escaping double quotes?

**Comment by bylee5** [comment]
What is the contents of the csv file?
The jsonb type in the csv file can be the form:
data.csv 
"{""s"":""test""}"
If so, then the next query can be executed.
CREATE FOREIGN TABLE testt (j jsonb)
SERVER import_server
OPTIONS( FORMAT 'csv', HEADER 'false', FILENAME '/path/to/data.csv');
