### ISSUE TITLE
Eager plan bug. Last item created not visible to next statement.

### ISSUE THREAD

**Issue by johnberzy-bazinga** [bitnine-oss/agensgraph#395]
Hello,

I'm running a build from source off of the master branch. I'm trying to execute a batch of statements, however, I'm stuck on an issue that I believe to be a bug. I've tried many variations with and with enable_eager set including adding it before the create clauses.

Vertices/Edges created are not visible to the match clause *directly* proceeding the create clause. However, if another create clause is inserted between the create/match the record is visible.   

Zero records returned in match
```
create vlabel foo;
create (:foo {bar : 'a'});
SET enable_eager = true;
match (a:foo {bar:'a'}) return a;
```

One record returned from match
```
create vlabel foo;
create (:foo {bar : 'a'});
create (:foo {bar : 'b'});
SET enable_eager = true;
match (a:foo {bar:'a'}) return a;
```

Thanks,
John

**Comment by htlim** [comment]
Hello, @johnberzy-bazinga 

This bug seems to be resolved before the next minor release.

Thank you for your detailed report.
H.T
