### ISSUE TITLE
Postgres 10.3 is not supported, can we update to 10.4.1?

### ISSUE THREAD

**Issue by pratikpparikh** [bitnine-oss/agensgraph#401]
Dear Authors,

Based on the link 10.3 is not supported can you please update the 10.3 base to 10.4.1 ? https://www.postgresql.org/support/versioning/

Regards,
Pratik Parikh

**Comment by gtyun** [comment]
Sorry, 10.4 is minor update , so it will be not included this release.
We are preparing release and the resource is not enough now.

**Comment by pratikpparikh** [comment]
@gtyun should I change this request to 11? and you can plan it for next release after 1.4.  I already started merging but soon found out that the customization is spread out?  If I do create a branch will someone sign up for validation post 1.4? if yes, would recommend with 11 or 10.4?

**Comment by gtyun** [comment]
@pratikpparikh 
Ok, we discussed with this issue and decided to merge 10.4.
