### ISSUE TITLE
set graph  path using psycopg2

### ISSUE THREAD

**Issue by VinACE** [bitnine-oss/agensgraph#408]
>>> cur = conn.cursor()
>>> cur.execute("MATCH (n:b) RETURN n Limit 10")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
psycopg2.ProgrammingError: graph_path is NULL
**HINT:  Use SET graph_path**

>>> cur.execute("SET graph_path=batch")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block

Hi to set this in the python code to access agensgraph db

Appreciate your help

**Comment by VinACE** [comment]
>>> cur.execute("SET graph_path = batch")

There has to be a space..

**Comment by gtyun** [comment]
This seems to be a psycopg's bug.
