### ISSUE TITLE
Loading multiple files into foreign table

### ISSUE THREAD

**Issue by VinACE** [bitnine-oss/agensgraph#412]
I have a table data in multile csv files,  with the  server import options how can I load, multiple csv files into the foreign table.

can I use copy command similar to the one below,
COPY forecasts
FROM 'tmp/forecast.csv'
CSV HEADER;  to load multiple csv files and that works for foreign table.

server import_server
options
(
 FORMAT 'csv',
 HEADER 'true',     //Indicates the presence of a csv header
 DELIMITER '|',
 NULL '',
 FILENAME '/path/to/comments.csv'
 );

**Comment by VinACE** [comment]
# COPY new_m
# FROM 'E4-02.csv'
# CSV HEADER;
ERROR:  cannot copy to foreign table "new_m"

**Comment by VinACE** [comment]
can you share some light, reference on  having external table, in hdfs or  on the unix filesystem to point to multiple files.. instead of single file..

**Comment by ontologiae** [comment]
It's a very Postgresql related question. I could suggest to ask you question to Stackoverflow, for instance.

**Comment by VinACE** [comment]
Sorry you can remove this question, Thanks for your support
