### ISSUE TITLE
Some commands are missing in the help

### ISSUE THREAD

**Issue by ykhwong** [bitnine-oss/agensgraph#417]
Could not see any of the following commands when typing _\h_ or _\help_ on the AgensGraph CLI, 
* CREATE VLABEL
* CREATE ELABEL
* DROP VLABEL
* DROP ELABEL

**master-branch**
> \h CREATE VLABEL
> No help available for "CREATE VLABEL".
> Try \h with no arguments to see available [help.]

They existed as of v1.3.1, but not in the latest master branch of AgensGraph.

**v.1.3.1**
> \h CREATE VLABEL
> Command:     CREATE VLABEL
> Description: define a new vertex label
> Syntax:
> CREATE [ UNLOGGED ] VLABEL [ IF NOT EXISTS ] vertex_label_name
> [ DISABLE INDEX ]
> [ INHERITS ( parent_vertex_label [, ... ] ) ]
> [ WITH ( storage_parameter [= value] [, ... ] ) ]
> [ TABLESPACE tablespace_name ]

**Comment by gtyun** [comment]
We had to add it in v1.3.1 roughly for some reason, it's contents was not verified. 
That's why it has not merged yet. We are going to review this issue again. Thank you for your report.
