### ISSUE TITLE
ran out of disk space around 150 GB for a very small dataset

### ISSUE THREAD

**Issue by VinACE** [bitnine-oss/agensgraph#419]
~> df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvdf       148G  141G  204K 100% /batchdata

MATCH (a: vendor), (b:plant) where b.bought_f_vendor= a.bought_f_vendor 
CREATE (a) - [r : bought_f_vendor] -> (b)
vendor_count 3356 on the left table and 236432  materials with vendor on the right table..

Unsure about the space usage to create the relationship

**Comment by illmatik12** [comment]
I'm not sure about this issue. 
Please check directory usage.  ( du -h )
Next, check actual relation size and vacuum it.

1. check relation size 
select
	table_name,
	pg_size_pretty(table_size) as table_size,
	pg_size_pretty(indexes_size) as indexes_size,
	pg_size_pretty(total_size) as total_size
	from
	(
		select
			table_name,
			pg_table_size(table_name) as table_size,
			pg_indexes_size(table_name) as indexes_size,
			pg_total_relation_size(table_name) as total_size
		from
			(
				select
					(
						'"' || table_schema || '"."' || table_name || '"'
					) as table_name
				from
					information_schema.tables
			) as all_tables
		order by
			total_size desc
	) as pretty_sizes;

2. Run vacuum analyze foo.bar  or vacuum full analyze

**Comment by VinACE** [comment]
This was because of a self Join issue
