### ISSUE TITLE
ERROR: btree index keys must be ordered by attribute, SQL Code->XX000, no graph

### ISSUE THREAD

**Issue by VinACE** [bitnine-oss/agensgraph#429]
[FAIL] DataAccessException->StatementCallback; uncategorized SQLException for
 SQL 
[
MATCH path = (m : mat { com:'10'} ) <- [r: com_2_mat ] - (mb: mat_b {} ) - [ *] ->(b) RETURN path;

]; SQL state [XX000]; error code [0]; ERROR: btree index keys must be ordered by attribute; nested exception is org.postgresql.util.PSQLException: ERROR: btree index keys must be ordered by attribute, SQL Code->XX000, no graph

I have created index for all the vertex labels, not sure why this is  pointing to 
similar to the below index creation scripts.
CREATE INDEX ON :mat(com);

**Comment by peter-ungvari** [comment]
Got the same error with version 2.1.0.

**Comment by protodef** [comment]
Fixed by #463.
