### ISSUE TITLE
How to create the PostGIS extension inside an AgensGraph database?

### ISSUE THREAD

**Issue by Geoneer** [bitnine-oss/agensgraph#430]
I want to use spatial queries from PostGIS inside my AgensGraph database. 
1. Is it possible to install the extension inside AgensGraph databases?
2. If yes, how do I install PostGIS inside AgensGraph server

a. I'm on windows 10 64bits
b. more trials here: https://github.com/Geoneer/smrtmps_ws/issues/33

**A.**
If it's not possible to get PostGIS inside AgensGraph:
1. Merge AgensGraph code with PostGresql DB source
2. Build new version of AgensGraph from a fork with PostGresql source
3. Install Postgresql database & PostGIS inside the new AgensGraph
4. Test the PostGIS extension inside new builded AgensGraph

**B**
Well... this is a lot of work I think.  So how about this:
1. Create extension from AgensGraph source
2. Create AgensGraph extension inside exisiting PostGresql database server
3. Install PostGIS inside the Postgresql database server
4. Use AgensGraph functionality together with PostGIS functions.

This seems to be als quite complicated I think.

**The Q's:**

1. What would you all think about this situation?
2. What is the most easy way of getting PostGIS inside an AgensGraph database?

**Comment by Geoneer** [comment]
Well.. I'm thinking a bit about this:
A. Use an AgensGraph database for the Graph Data 
B. Use an PostGresql + PostGIS database for the Geographical Data
C. Connect the data 'over'  the databases and keep them connected  with smart queries. 
D. In MSSQL Server something alike is possible to query 'over' different databases with remote connections. This is also possible with a webservice connected to both databases. But yeah.. it's a big work around......

**Comment by Geoneer** [comment]
Another option is to create the postgis function I need with the postgis sql functions from the postgresl + postgis install.

Maybe it s possible to create the functions inside agensgraph 'by hand'?

**Comment by Geoneer** [comment]
creating the postgis funtions ' by hand'  inside the agensgraph db did not work. I did split up the graph and geo-data inside two databases:
- graph = agens
- geom  = postgresql + postgis.

Now I want to relate the geom objects with the vertex id of the graphid to connect the geometry and the graph vertex. This is how I want to connect the vertexes with geometry.

**Comment by mcaramma** [comment]
This might possibly help you https://github.com/mcaramma/sv2/blob/master/Dockerfile#L153

**Comment by Geoneer** [comment]
@mcaramma Thanks for your reply.... But what is it? I don't know how this might work. 

And I like to keep it simple, but it looks quite complicated. 

I did setup now 2 system servers: 
1. Graph database
2. PostGIS database

And I refer from the PostGIS database with [points,polygons,lines] to the attributes inside the graph database. In fact it works well, but from architecture point of view I don't want this. 

Also Agens Graph does put in their documents that POSTGIS is easy to implement... 

So how do they do that?

**Comment by mcaramma** [comment]
Hi @Geoneer the link point to the steps I use to compile PostGIS on top of AgensGraph, don't bother with the rest.

If you already know how to build AgensGraph successfully from source this is how you build PostGIS on top of it as an extension
```
POSTGIS_VERSION="2.5.0"
apt-get -y install libxml2-dev libgeos-dev libgdal-dev libproj-dev \
    && cd /usr/local/src \
    && wget -c https://download.osgeo.org/postgis/source/postgis-${POSTGIS_VERSION}.tar.gz \
    && tar zxvf postgis-${POSTGIS_VERSION}.tar.gz \
    && cd postgis-${POSTGIS_VERSION} \
    && ./configure \
    && make \
    && make install
```
Then run https://github.com/mcaramma/sv2/blob/master/initdb-postgis.sh

This should answer to your questions in the first comment above:

1. Is it possible to install the extension inside AgensGraph databases?
2. If yes, how do I install PostGIS inside AgensGraph server?

**Comment by Geoneer** [comment]
@mcaramma 

Yes! that's a good idea to build the whole stuff from the source up by myself. 

And implement the POSTGIS inside the Agens Graph build itself. I will give this a try and setup an issue for my project. 

Thanks for your fresh idea! #likes

**Comment by Geoneer** [comment]
https://github.com/Geoneer/smrtmps_ws/issues/81

**Comment by dahaynes** [comment]
I'm running into an error trying to enable the postgis extension on AgensDB (a fork of PostgreSQL). My setup is on a windows machine, PSQL 10.4. I have done this sucessfully once before, but I am unable to replicate it on my new machine.

The process I used is the following. I downloaded the precompiled windows binaries (postgis-bundle-pg10x64-setup-2.5.1-1.exe) and executed it within the agens directory successfully, but it still errors. The error below is strange because the file exists within the directory.

agens -p 5433 -U agens -c "CREATE EXTENSION postgis"
ERROR:  could not load library "C:/AgensGraph-2.1.0/lib/rtpostgis-2.5.dll": The specified module could not be found.

**Comment by mcaramma** [comment]
@dahaynes I'm unable to help you with Windows issues.

Anyway, you may want to try to locate `rtpostgis-2.5.dll` file in your system and make a copy of it inside `C:/AgensGraph-2.1.0/lib/` ... I guess this will be an iterative work over several DLL.

This may work or not, I've no idea, last time I touched a Windows machine was 20 years ago.

**Comment by dahaynes** [comment]
the file is in the correct path. According other postgresql folks there is
something else happening.
Do you have complete AgensGraph DB packages that support all PostgreSQL
extensions available for download?

**Comment by mcaramma** [comment]
You may want to copy the snippets you find interesting from here https://github.com/mcaramma/sv2/blob/master/Dockerfile

Others have been successfull compiling AgensGraph with all the extensions listed in there.

**Comment by Geoneer** [comment]
I did step over to Neo4J with spatial analyse functions.
