### ISSUE TITLE
Support for Postgres 11.

### ISSUE THREAD

**Issue by pratikpparikh** [bitnine-oss/agensgraph#456]
Dear Owners,

      When is the next planned release for upgrading to the latest Postgres 11.1?

Regards,
Pratik Parikh

**Comment by gtyun** [comment]
The plan is May but I'm not sure.

**Comment by pratikpparikh** [comment]
no worries just want to add the issue so it can be addressed at some point in near future.  Please let me know if i can help.  Also hoping we will take the latest when we do next update.

**Comment by pratikpparikh** [comment]
@gtyun  any update on this?
