### ISSUE TITLE
question: What is the difference between pg_ctl vs ag_ctl command?

### ISSUE THREAD

**Issue by pratikpparikh** [bitnine-oss/agensgraph#459]
Dear Contributor,
   
What is the key difference between ag_ctl and pg_ctl?

Regards,
Pratik Parikh

**Comment by gtyun** [comment]
ag_ctl shows version info of AgensGraph, instead of PostgreSQL. 
And the environment variable AGDATA takes precedence over PGDATA.
There is nothing very special.

**Comment by pratikpparikh** [comment]
Thank you @gtyun
