### ISSUE TITLE
The create clause makes me confused

### ISSUE THREAD

**Issue by zzl221000** [bitnine-oss/agensgraph#460]
Agensgraph supports unique indexes, but when using the create clause, it seems that there is no solution to the unique index conflict.
Or, how should I use ON CONFLICT?
`create(:node {name:'Jim',id:'12345'}),(:node {name:'Jim',id:'12345'});`
I want this create clause to execute and ignore the unique index conflict

**Comment by gtyun** [comment]
We didn't implement ON CONFLICT clause.  As far as I know there is no such syntax in the Cypher spec. If you find it, please let me know. And if what you want is ON CONFLICT DO NOTHING, you can replace it with MERGE clause.
