### ISSUE TITLE
Query runs forever when I want the complete path, but returns immediately when I only want a sub-element

### ISSUE THREAD

**Issue by pebbe** [bitnine-oss/agensgraph#495]
AgensGraph 2.1.2, based on PostgreSQL 10.4

I have this query that gives a result immediately (there are no matches, every `word` has a `sentid`):
```
match (:word{lemma:'fietsen'})<-[:next*]-(w:word{lemma:'gaan'}) return w.sentid;
```
When I change the query to this, it runs forever:
```
match p = (:word{lemma:'fietsen'})<-[:next*]-(w:word{lemma:'gaan'}) return p;
```

The match is the same, right?

With explain, I get this:
```
=> explain match (:word{lemma:'fietsen'})<-[:next*]-(w:word{lemma:'gaan'}) return w;
                                          QUERY PLAN                                          
----------------------------------------------------------------------------------------------
 Nested Loop  (cost=6.01..4224.78 rows=1 width=32)
   ->  Bitmap Heap Scan on word "<0000000050>"  (cost=4.73..161.80 rows=40 width=8)
         Recheck Cond: (properties.'lemma'::text = '"fietsen"'::jsonb)
         ->  Bitmap Index Scan on word_lemma_idx  (cost=0.00..4.72 rows=40 width=0)
               Index Cond: (properties.'lemma'::text = '"fietsen"'::jsonb)
   ->  Nested Loop  (cost=1.27..101.56 rows=1 width=433)
         ->  Nested Loop VLE [1..]  (cost=0.85..17.01 rows=10 width=64)
               ->  Index Scan using next_end_idx on next l  (cost=0.42..8.44 rows=1 width=48)
                     Index Cond: ("<0000000050>".id = "end")
               ->  Index Scan using next_end_idx on next r  (cost=0.42..8.44 rows=1 width=16)
                     Index Cond: ($1 = "end")
         ->  Index Scan using word_pkey on word w  (cost=0.42..8.45 rows=1 width=433)
               Index Cond: (id = l.start)
               Filter: (properties.'lemma'::text = '"gaan"'::jsonb)
(14 rows)
```
And (after much more time than the previous one):
```
=> explain match p = (:word{lemma:'fietsen'})<-[:next*]-(w:word{lemma:'gaan'}) return p;
                                                        QUERY PLAN                                                        
--------------------------------------------------------------------------------------------------------------------------
 Hash Join  (cost=1988.99..7892.34 rows=4 width=32)
   Hash Cond: (w.id = l.start)
   ->  Bitmap Heap Scan on word w  (cost=77.69..5891.13 rows=1711 width=433)
         Recheck Cond: (properties.'lemma'::text = '"gaan"'::jsonb)
         ->  Bitmap Index Scan on word_lemma_idx  (cost=0.00..77.26 rows=1711 width=0)
               Index Cond: (properties.'lemma'::text = '"gaan"'::jsonb)
   ->  Hash  (cost=1892.80..1892.80 rows=1480 width=505)
         ->  Nested Loop  (cost=5.58..1892.80 rows=1480 width=505)
               ->  Bitmap Heap Scan on word "<0000000052>"  (cost=4.73..161.80 rows=40 width=433)
                     Recheck Cond: (properties.'lemma'::text = '"fietsen"'::jsonb)
                     ->  Bitmap Index Scan on word_lemma_idx  (cost=0.00..4.72 rows=40 width=0)
                           Index Cond: (properties.'lemma'::text = '"fietsen"'::jsonb)
               ->  Nested Loop VLE [1..]  (cost=0.85..42.53 rows=37 width=192)
                     ->  Index Scan using next_end_idx on next l  (cost=0.42..8.44 rows=1 width=112)
                           Index Cond: ("<0000000052>".id = "end")
                     ->  Nested Loop  (cost=0.42..33.67 rows=4 width=80)
                           ->  Index Scan using next_end_idx on next r  (cost=0.42..8.44 rows=1 width=35)
                                 Index Cond: ("end" = $1)
                           ->  Append  (cost=0.00..25.19 rows=4 width=234)
                                 ->  Seq Scan on ag_vertex vtx  (cost=0.00..0.00 rows=1 width=46)
                                       Filter: (id = $1)
                                 ->  Index Scan using sentence_pkey on sentence vtx_1  (cost=0.29..8.31 rows=1 width=343)
                                       Index Cond: (id = $1)
                                 ->  Index Scan using node_pkey on node vtx_2  (cost=0.42..8.44 rows=1 width=115)
                                       Index Cond: (id = $1)
                                 ->  Index Scan using word_pkey on word vtx_3  (cost=0.42..8.44 rows=1 width=433)
                                       Index Cond: (id = $1)
(27 rows)
```

**Comment by pebbe** [comment]
Could this be related to https://github.com/bitnine-oss/agensgraph/issues/493 ?

**Comment by pebbe** [comment]
These both return immediately:
```
match p = (:word{lemma:'fietsen'})<-[:next]-(w:word{lemma:'gaan'}) return p;
match p = (:word{lemma:'fietsen'})<-[:next*2]-(w:word{lemma:'gaan'}) return p;
```
This one never returns:
```
match p = (:word{lemma:'fietsen'})<-[:next*3]-(w:word{lemma:'gaan'}) return p;
```

**Comment by jrgemignani** [comment]
Try adding count() to see how many results it is going to retrieve -

match p = (:word{lemma:'fietsen'})<-[:next*3]-(w:word{lemma:'gaan'})
return count(p);

**Comment by pebbe** [comment]
With `return count(p)` it also runs forever.

And...
```
me=> match p = (:word{lemma:'fietsen'})<-[:next*3]-(w:word{lemma:'gaan'}) return count(w);
^CCancel request sent
ERROR:  canceling statement due to user request
me=> match (:word{lemma:'fietsen'})<-[:next*3]-(w:word{lemma:'gaan'}) return count(w);
 count 
-------
 0
(1 row)
```

**Comment by jrgemignani** [comment]
How much time are you giving it to run, that it runs forever?

Some queries, especially ones that have variable length paths, can run for
a long time on a small graph because it has to look at all the variations
of the paths to the target nodes.

The count() query should run faster as it isn't buffering the results for
output.

john

**Comment by pebbe** [comment]
I just let it run 15 minutes. No result. 100% CPU usage. No increase in memory usage.

**Comment by jrgemignani** [comment]
How many nodes and edges are in the graph?

match (n) return count(n);
match ()-[e]-() return count (e);

Also, about the original question about the two queries being the same,...

One query is compiling a list of nodes that match a criteria and then
listing a particular characteristic of those nodes. While the other query
is compiling a list of paths that match the criteria and then listing those
paths.

John

**Comment by pebbe** [comment]
There are  1,158,502 nodes and 8,410,384 edges. The graph is devided into 40,524 subgraphs that are not connected to eachother.

**Comment by pebbe** [comment]
If you want to, you can download the input for creating the graph here:
https://urd2.let.rug.nl/~kleiweg/cypher/

It's 61Mb, and takes one to two hours to insert into AgensGraph.

**Comment by jrgemignani** [comment]
For that graph, you have an average of 7.3 edges per node, which is a
fairly dense graph.

So, even if it is divided into many subgraphs, it will still need to go
through all of the nodes and their edges, those children nodes and their
edges, and their children, etc. Each level being roughly a power of 7 more
than the last, until it resolves them all. Add in cyclic paths, and there
ends up being a lot of paths to process.

If you look at the results of the explain command, you can see that the
later command is deeply nested compared to the former. So, it will take
longer to execute. How long, I can't say. You may want to try running the
command with count() in it and just let it run for a while to find out how
many paths it finds.

There could also be some pathology in the graph causing this.

John

**Comment by pebbe** [comment]
Nodes of type `word` have only zero or one relation of type `next` to another node of type `word` and there are no loops with relations of type `next`.

The attribute `lemma` on `word` is indexed:

```
CREATE PROPERTY INDEX ON word("lemma");
```

Below, I set the required length the path to three.

AgensGraph finds all the relative parts very quickly:
```
me=> \timing 
Timing is on.

me=> match (w:word{lemma:'fietsen'}) return count(w);
 count 
-------
 10
(1 row)

Time: 2,346 ms

me=> match (w:word{lemma:'gaan'}) return count(w);
 count 
-------
 1549
(1 row)

Time: 24,113 ms

me=> match (w)<-[:next*3]-() return count(w);
 count  
--------
 592264
(1 row)

Time: 2975,380 ms (00:02,975)

me=> match (w:word{lemma:'fietsen'})<-[:next*3]-(:word{lemma:'gaan'}) return count(w);
 count 
-------
 0
(1 row)

Time: 2,585 ms

me=> match p = (w:word{lemma:'fietsen'})<-[:next*3]-(:word{lemma:'gaan'}) return count(p);
^CCancel request sent
ERROR:  canceling statement due to user request
```

The last query takes 18 ms in Neo4j on the same data.

And look at these. They are the virtually identical, but the first gives a result very quickle, while the second runs forever:
```
me=> match p = (w:word{lemma:'fietsen'})<-[:next]-()<-[:next*2]-(:word{lemma:'gaan'}) return count(p);
 count 
-------
 0
(1 row)

Time: 14,343 ms

me=> match p = (w:word{lemma:'fietsen'})<-[:next*3]-(:word{lemma:'gaan'}) return count(p);
^CCancel request sent
ERROR:  canceling statement due to user request
```

**Comment by jrgemignani** [comment]
I will load the data in the latest version and see if it has the same
issues.

john

**Comment by jrgemignani** [comment]
I just wanted to let you know that I had issues loading that data into the
latest version. I am looking into why it is a problem.

John

**Comment by erik-overdahl** [comment]
> Could this be related to #493 ?

I agree that this seems similar to the problem that I had (which never received any answer).

Can you try running the same query without direction on the edge?

```
match p = (:word{lemma:'fietsen'})-[:next*3]-(w:word{lemma:'gaan'}) return p;
```

That worked for me, but is obviously less than ideal, as the direction of the relationship often matters.

**Comment by pebbe** [comment]
Without direction, and with the direction the other way, it returns immediately. Perhaps because there are only a few matches for `(:word{lemma:'fietsen'})`
```
match p = (:word{lemma:'fietsen'})-[:next*3]->(:word{lemma:'gaan'}) return count(p);
```

**Comment by jrgemignani** [comment]
Hi Peter,

Sorry for the delay in getting back to you on this. There was an issue with
loading your dataset that we needed to resolve first.

To answer your question, yes, it appears that this is related to issue
#493. Time permitting, I will take a look at this issue.

John

**Comment by jrgemignani** [comment]
Hi Peter,

I want to thank you for the dataset. We were able to use it to find a bug
in the VLE code.

I am currently testing a fix for it.

John

**Comment by jrgemignani** [comment]
There is a fix in review for this issue. It was able to correct Peter's queries and allow them to successfully complete within a second.

John

**Comment by jrgemignani** [comment]
The fix has been applied to the latest source for Agensgraph. It should resolve the issues with variable length queries.
