### ISSUE TITLE
Support Postgresql 11?

### ISSUE THREAD

**Issue by lifejuggler** [bitnine-oss/agensgraph#510]
Is there any plan to support Postgresql 11? It would be nice to get sharding that comes with the version 11

**Comment by jrgemignani** [comment]
We are looking at supporting PostgreSQL 11. However, there is no date at
this time.

John

**Comment by lifejuggler** [comment]
Thanks for the quick response! Is there some roadmap/plan that I can take a look at? I am in the process of evaluating DBMS solutions for my company and would like to know if agensgraph would be a good candidate and scalability is definitely one of the more important requirements

**Comment by jrgemignani** [comment]
Hi Tom,

Eya Badal Abdisho (eya.abdisho@bitnine.net) should be able to help you here.

I have added her to this email chain.

John

**Comment by lifejuggler** [comment]
thank you!

**Comment by emotionbug** [comment]
Duplicate issue with #532
