### ISSUE TITLE
version() doesn't return agensgraph version

### ISSUE THREAD

**Issue by j616** [bitnine-oss/agensgraph#520]
From the docs:
```
version()
Returns AgensGraph’s version info.

----

SELECT version();

Result:
                                version    
-------------------------------------------------------------------------------
 PostgreSQL 9.6.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 
 (Red Hat 4.4.7-17), 64-bit
```

The returned version info is the Postgres version info, not the AgensGraph info as stated in the docs. Is there a functional way to get the AgensGraph version info? Can this bug be fixed/the docs corrected?

**Comment by emotionbug** [comment]
You can use **agversion** as an alternative.

```
SHOW agversion;

Result:
agversion    
--------------
2.2devel
```

**Comment by j616** [comment]
Cheers. We abandoned trying to use agensgraph several months back. We ran into too many bugs, places it didn't conform to spec, lack of documentation, and a complete lack of support even for basic issues like this. To put it concisely, it's not production ready.
