### ISSUE TITLE
feature or bug? -- head() and last() convert edge to json

### ISSUE THREAD

**Issue by pebbe** [bitnine-oss/agensgraph#525]
The AgensGraph Developer Manual for `head()` says: *Returns the first element in the list.*

It doesn't mention that the element may be converted to another type.

Below is an example with `head()`. With `last()` you get similar results.

Is this a feature or a bug? If it's a feature, then perhaps the documentation should mention this?

```
peter=# match (:node)-[r:rel*2]->(:node)
return r[0]
limit 1;
                        r                         
--------------------------------------------------
 rel[11.2][5.1,5.2]{"rel": "--", "primary": true}
(1 row)

peter=# match (:node)-[r:rel*2]->(:node)
return head(r) 
limit 1;
                                                    head                                                    
------------------------------------------------------------------------------------------------------------
 {"id": "11.2", "end": "5.2", "tid": "(0,2)", "start": "5.1", "properties": {"rel": "--", "primary": true}}
(1 row)
```

**Comment by jrgemignani** [comment]
Hi Peter,

I'm not sure what the reason is for having the array operation have a
different result type from the head operation.

I will bring this to the attention of those responsible.

Thanks!

John
