### ISSUE TITLE
Support for Postgres 13?

### ISSUE THREAD

**Issue by Hadryan** [bitnine-oss/agensgraph#532]

**Comment by turicas** [comment]
I'm not part of the development team and don't know the plans, but if you need support on other PostgreSQL versions, you may want to use the [AGE extension](https://age.apache.org/).

**Comment by Hadryan** [comment]
@turicas  AGE is not yet complete and is in incubating phase right now. Furthermore, it's not the same as original Agensgraph and lacks many functionalities Agensgraph already has.

**Comment by emotionbug** [comment]
@Hadryan yes, I agreed that you said. Internally, we are considering supporting PG 12. but, this is not decided yet.
because, developers is busy now because of developing AGE.

**Comment by Hadryan** [comment]
## Please don't let this awesome piece of software, (**Agensgraph**)  die. 

After we successfully implemented it on our educational project with at least +500K new rows of data added each day, I can confirm Agensgraph is doing its job so beautifully and perfectly, without any deficiency.

In our production environment Agensgraph is responsible for doing very heavy tasks of social networks and recommendation systems! 

The only downside of current Agensgraph version (v2.1.3), is not supporting those great improvements of PostgreSQL versions 12 and 13. And the lack of some functions currently exists on other graph databases like UNWIND, which I believe is possible to achieve in the next generation of Agensgraph.

**P.S:** Before choosing Agensgraph as the backbone of our production environment, we tried dozens of other graph databases!

**Comment by gorgonzola-oh** [comment]
Apache AGE will.
[https://github.com/apache/incubator-age](url)

**Comment by Hadryan** [comment]
@gorgonzola-oh As we pointed this [before](https://github.com/bitnine-oss/agensgraph/issues/532#issuecomment-825612351), AGE is not as mature as the original Agensgraph right now and with much less functionalities Agensgraph already supports. AGE version 1 would be ready in mid 2022

**Comment by aysko75** [comment]
@Hadryan Thank you for such keen attention and interest in AgensGraph and AGE. As one of people deeply involved with the development efforts happening around AgensGraph and AGE at Bitnine, I can say we are very positively looking into the possibility of upgrading AgensGraph to support PostgreSQL 12 before this year ends. As for the Apache AGE project, the current release can support some basic graph operations using Cypher queries. Being an extension, there can be some AgensGraph functionalities AGE cannot support simply because there are some limits an extension get around. Our plan is to release a production-level version of AGE in Q3 this year. AgensGraph will not die :)

**Comment by aysko75** [comment]
@Hadryan please check out AG Cloud Express at agcloud.bitnine.net ... AgensGraph + AGViewer on Cloud ... AG Cloud will be ready in Q3

**Comment by Hadryan** [comment]
Awesome news! thanks @aysko75

**Comment by emotionbug** [comment]
in privately, i try to upgrade PG version.
If anyone is interested, please join this. :) 
When the work is done, I will PR to the current repository.

https://github.com/emotionbug/agensgraph-compare-orig/tree/agensgraph
https://travis-ci.com/github/emotionbug/agensgraph-compare-orig/builds/226164447

**Comment by shayneoneill** [comment]
Yeah this would be really good. While we're waiting for AGE to get production ready, Agensgraph is stuck on a postgres version a lot of the worlds gone past many years ago. I've tried compiling it against 12 and it doesnt seem to be compatible (I wont lie, these sorts of codebases are well out of my depth)
