### ISSUE TITLE
How to remove quotes from text. btrim() not working in Cypher

### ISSUE THREAD

**Issue by joefagan** [bitnine-oss/agensgraph#535]
btrim() not working in Cyper but works using Hybrid query
```
DROP GRAPH IF EXISTS btrim CASCADE;
CREATE GRAPH btrim;
SET graph_path = btrim;

CREATE ({name:'Adam'});
MATCH (n) RETURN btrim(n.name::text,'"');
```
 "Adam"
(1 row)

quotes are not removed
```
SELECT btrim(name::text,'"') 
FROM (
    MATCH (n) RETURN n.name AS name
) AS x;
```
 Adam
(1 row)

quotes correctly removed.

**Comment by emotionbug** [comment]
`btrim` function works. However, the reason why it does not work as intended is that it returns the data with `jsonb` type.
Therefore, it can be removed as below.

```pgsql
SELECT name #>> '{}' FROM (MATCH (n) RETURN n.name) cypher;
```

https://www.postgresql.org/docs/9.3/functions-json.html
#>> | array of text | Get JSON object at specified path as text | '{"a":[1,2,3],"b":[4,5,6]}'::json#>>'{a,2}'
-- | -- | -- | --

**Comment by joefagan** [comment]
Thank you @emotionbug
