### ISSUE TITLE
What query is similar to INSERT RETURNING ID in cypher?

### ISSUE THREAD

**Issue by afidegnum** [bitnine-oss/agensgraph#539]
`CREATE (s:snode {name: 'John', from: 'USA', age: 17}) RETURNING s;` returns an error. 

I'm automating an insertion, I want to be able to grab the last inserted id and pass it to the next iteration.

**Comment by emotionbug** [comment]
in cypher using `RETURN` statement.

**Comment by afidegnum** [comment]
It didn't work out

**Comment by emotionbug** [comment]
That error is occured in JDBC with your code.

https://github.com/pgjdbc/pgjdbc/blob/8be516d47ece60b7aeba5a9474b5cac1d538a04a/pgjdbc/src/main/java/org/postgresql/util/PSQLState.java#L43 

Could you tell me how to reproduce it?

**Comment by afidegnum** [comment]
I only inserted a single query using via agensbrowser.

**Comment by emotionbug** [comment]
ROFL... I will look into it.
How about use AGViewer or psql?

**Comment by afidegnum** [comment]
sorry I mean AGViewer, I tried with Psql and python and had a similar issue. 
Can you please also advise what step do i need to take in case I want to build a agensclient in Rust ??

**Comment by emotionbug** [comment]
i can't reproduce it your issue.

```
# psql -U postgres
psql (10.4)
Type "help" for help.

postgres=# create graph test;
CREATE GRAPH
postgres=# set graph_path='test';
SET
postgres=# CREATE (p:person {name: 'Daniel', from: 'Korea', age: 20}) RETURN p;
                             p
-----------------------------------------------------------
 person[3.1]{"age": 20, "from": "Korea", "name": "Daniel"}
(1 row)
```

https://github.com/sfackler/rust-postgres/issues/466
hmm... rust driver need to develop.

**Comment by afidegnum** [comment]
exactly the same query I did, I will give it a try again. 

I'm highly motivated about rust development. since that's my main development language., 
I have come across lots of graph database but i'm more comfortable with this one since I can both use both RDMS and Graph query at the same time. I only pray for this product to sustain for a long period of time

**Comment by joefagan** [comment]
![image](https://user-images.githubusercontent.com/48284776/128418991-3b2c3172-45a3-44ca-97d3-b134bf610f10.png)
Works for me as expected in agcloud.bitnine.net -> AGviewer

**Comment by afidegnum** [comment]
Thanks, I was having the problem rather on AgensBrowser. I couldn't run AGviewer, how did you run it? i followed the nodejs installation procedure

**Comment by joefagan** [comment]
Go agcloud.bitnine.net -> add a new project -> choose the first tutorial -> launch AGviewer
You can then create your graph in the query editor of AGviewer.
Skim through this tutorial https://www.youtube.com/watch?v=8S1IJswl7Lg&t=31s

**Comment by emotionbug** [comment]
@afidegnum instead, you can use docker.
```
docker run \
    --publish=3001:3001 \
    --name=agviewer \
    bitnine/agviewer:latest
```
