### ISSUE TITLE
How do i search by id? 

### ISSUE THREAD

**Issue by afidegnum** [bitnine-oss/agensgraph#540]
None of these query worked. 
```

MATCH (p:Person {id(p): '3.2'}) return p;

MATCH (p:Person {id: '3.2'}) return p;

MATCH (p:Person {vid: '3.2'}) return p;
```
which one works?

**Comment by emotionbug** [comment]
Use this.

```
MATCH (p:Person) WHERE id(n) = 3.14 return p;
```

**Comment by afidegnum** [comment]
Thanks a lot,

**Comment by afidegnum** [comment]
it's rather `p` not `n` 
`MATCH (p:Person) WHERE id(p) = 3.14 return p;`

**Comment by emotionbug** [comment]
you are right.

**Comment by afidegnum** [comment]
Another little question again, what will be the query if i want to match 2 edges by id? 
`MATCH (p:person {name: 'John'}),(k:person{name: 'Daniel'}) CREATE (p)-[:knows]->(k)`
so, instead of matching by name, i want to match by ID

**Comment by emotionbug** [comment]
use like this.
```
MATCH (p:person),(k:person)
WHERE id(p) = 1 AND id(k) = 2
CREATE (p)-[:knows]->(k)
```

**Comment by afidegnum** [comment]
thanks
