### ISSUE TITLE
www.agensgraph.org shows 403 Forbidden

### ISSUE THREAD

**Issue by beepsoft** [bitnine-oss/agensgraph#549]
Actually all of bitnine.net is 403, so no documentation is available.

**Comment by joefagan** [comment]
Not aware of any issues. Please retry and let us know.

**Comment by beepsoft** [comment]
I still get 403. I tried from different networks/machines with the same result. I try to connect from Hungary if that helps.

![image](https://user-images.githubusercontent.com/1926265/149545581-849a77ce-e9bf-4da1-bdee-cdd0d1f60fb6.png)

**Comment by joefagan** [comment]
I'll raise this with out IT dept.
Meanwhile here are some things to check your end...

https://www.howtogeek.com/357785/what-is-a-403-forbidden-error-and-how-can-i-fix-it/

**Comment by akloster** [comment]
This is still the case for me for both agensgraph.org and bitnine.net.

**Comment by beepsoft** [comment]
And again.

I now tried this https://www.screenshotmachine.com/website-screenshot-generator.php service, whether it can see the site and got this:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/1926265/167585895-74914407-f144-4765-8428-18d4de343c08.png">

**Comment by gorgonzola-oh** [comment]
Hey, It seems to be fixed now. Please try again.

**Comment by gliljas** [comment]
And now the SSL certificate has expired.

**Comment by gorgonzola-oh** [comment]
now It's good.
