### ISSUE TITLE
pg_12_12: with-llvm flag failed regression

### ISSUE THREAD

**Issue by emotionbug** [bitnine-oss/agensgraph#562]
EEOP_CYPHER* Operation is not implemented in llvm_compile_expr() ( llvmjit_expr.c )

**Comment by emotionbug** [comment]
must use clang to use LLVM.

**Comment by ibrarahmad** [comment]
I am using CLANG now and it compiled successfully.

**Here is compile log**
```
clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2 -fstrict-enums -fno-signed-zeros -fPIC -I. -I. -I/usr/include/python2.7 -I../../../src/include  -D_GNU_SOURCE   -c -o plpy_typeio.o plpy_typeio.c
clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2 -fstrict-enums -fno-signed-zeros -fPIC -I. -I. -I/usr/include/python2.7 -I../../../src/include  -D_GNU_SOURCE   -c -o plpy_util.o plpy_util.c
clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2 -fstrict-enums -fno-signed-zeros -fPIC -shared -o plpython2.so plpy_cursorobject.o plpy_elog.o plpy_exec.o plpy_main.o plpy_planobject.o plpy_plpymodule.o plpy_procedure.o plpy_resultobject.o plpy_spi.o plpy_subxactobject.o plpy_typeio.o plpy_util.o  -L../../../src/port -L../../../src/common   -L/usr/lib/llvm-10/lib  -Wl,--as-needed -Wl,-rpath,'/usr/lib/python2.7/config-x86_64-linux-gnu',--enable-new-dtags  -L/usr/lib/python2.
```
At what stage you are getting this error and what configuration parameter are you using.

**Here are my configuration.**

`CC=clang CFLAGS="-O0  -fstrict-enums -fno-signed-zeros" ./configure --prefix=/usr/local/pgsql.ag/ --with-llvm LLVM_CONFIG='/usr/bin/llvm-config' --enable-cassert --with-python --with-perl --enable-tap-tests && make -j 12
`

**Comment by emotionbug** [comment]
Compiling is not problem. run the test.

**Comment by emotionbug** [comment]
It's just my mistake to close it. Nothing has been solved, so I won't close it.
I also attach CI results for this error.

https://github.com/emotionbug/agensgraph/runs/7196760073

**Comment by ibrarahmad** [comment]
You need to specify these options too, Its documented options.

`CC=clang CFLAGS="-O0 -fstrict-enums -fno-signed-zeros"`

**Comment by emotionbug** [comment]
If you need this option, it's another issue, and regardless of this, ofcursely, regression fails.

**Comment by yjy44** [comment]
@emotionbug is working on this job from now.

**Comment by emotionbug** [comment]
Fixed with https://github.com/bitnine-oss/agensgraph/commit/dcc609c035f89eabe7143c0e3fc8ebcf0064c35c
