### ISSUE TITLE
Docker Image v2.5.0 ?

### ISSUE THREAD

**Issue by walter-weinmann** [bitnine-oss/agensgraph#566]
Is there a reason why the Docker image has not been updated for some time? The last version is v2.5.0 and 9 months old.

https://hub.docker.com/r/bitnine/agensgraph

**Comment by emotionbug** [comment]
We managed the Dockerfile separately, which resulted in omission.
So, I'm thinking about the direction of managing Dockerfile in this repository.
It will be solved soon.

**Comment by yjy44** [comment]
We updated v2.12.0. If possible, please check and use it.
