### ISSUE TITLE
agensbrowser installation issue/ can't create any graph

### ISSUE THREAD

**Issue by coulibalyfagnine** [bitnine-oss/agensgraph#576]
Hello everybody,
I am new in the agensgraph and agensBrowser world.
I have installed both agensgraph and agensBrower on my windows 10 machine. But I can't create any graph database.
Here is the error message : **[FAIL] DataAccessException->Could not get JDBC Connection; nested exception is org.postgresql.util.PSQLException: ERROR: invalid value for parameter "graph_path": "agens"
  Détail : graph "agens" does not exist., SQL Code->22023**

Can somebody help me please ?  

![Issue to create a graph data base](https://user-images.githubusercontent.com/59516073/185046333-895b8d00-8a3c-4ddd-9a66-eeff8cf0510d.png)

**Comment by fourmicao** [comment]
Agensbrowser can only connect to a dedicated graph configured in conf file. You cannot create new graph.

**Comment by coulibalyfagnine** [comment]
Thank you for your response
