### ISSUE TITLE
Agensgraph : scripts which are part of pgdump failing in restore

### ISSUE THREAD

**Issue by ns-berumalu** [bitnine-oss/agensgraph#587]
We are using agensgraph of version v2.12 for our environment. I have taken a db backup using pg_dump and when we are trying to restore it a few inserts scripts which are part of the backups failing in restore. Could you please suggest this issue?

Below are the scripts which are part of pgdump backup.

INSERT INTO pg_catalog.ag_graph

(SELECT nspname, oid FROM pg_catalog.pg_namespace

WHERE nspname = 'xxx');

INSERT INTO pg_catalog.pg_depend

(SELECT 2615, nspid, 0, 7040, oid, 0, 'i'

FROM pg_catalog.ag_graph);

INSERT INTO pg_catalog.ag_label

(SELECT c.relname, g.oid, 1, c.oid, 'v'

FROM pg_catalog.ag_graph g

JOIN pg_catalog.pg_namespace n ON n.oid = g.nspid

JOIN pg_catalog.pg_class c ON c.relnamespace = n.oid

WHERE g.graphname = 'xxx' AND c.relname = 'ag_vertex');

INSERT INTO pg_catalog.ag_label

(SELECT c.relname, g.oid, 2, c.oid, 'e'

FROM pg_catalog.ag_graph g

JOIN pg_catalog.pg_namespace n ON n.oid = g.nspid

JOIN pg_catalog.pg_class c ON c.relnamespace = n.oid

WHERE g.graphname = 'xxx' AND c.relname = 'ag_edge');

INSERT INTO pg_catalog.ag_label

(SELECT c.relname, g.oid, 3, c.oid, 'e'

FROM pg_catalog.ag_graph g

JOIN pg_catalog.pg_namespace n ON n.oid = g.nspid

JOIN pg_catalog.pg_class c ON c.relnamespace = n.oid

WHERE g.graphname = 'xxx' AND c.relname = 'owns');

INSERT INTO pg_catalog.ag_label

(SELECT c.relname, g.oid, 4, c.oid, 'e'

FROM pg_catalog.ag_graph g

JOIN pg_catalog.pg_namespace n ON n.oid = g.nspid

JOIN pg_catalog.pg_class c ON c.relnamespace = n.oid

WHERE g.graphname = 'xxx' AND c.relname = 'refers');

INSERT INTO pg_catalog.ag_label

(SELECT c.relname, g.oid, 5, c.oid, 'v'

FROM pg_catalog.ag_graph g

JOIN pg_catalog.pg_namespace n ON n.oid = g.nspid

JOIN pg_catalog.pg_class c ON c.relnamespace = n.oid

WHERE g.graphname = 'xxx' AND c.relname = 'xxx');

INSERT INTO pg_catalog.ag_label

(SELECT c.relname, g.oid, 6, c.oid, 'v'

FROM pg_catalog.ag_graph g

JOIN pg_catalog.pg_namespace n ON n.oid = g.nspid

JOIN pg_catalog.pg_class c ON c.relnamespace = n.oid

WHERE g.graphname = 'xxx' AND c.relname = 'xxx');

INSERT INTO pg_catalog.ag_label

(SELECT c.relname, g.oid, 7, c.oid, 'v'

FROM pg_catalog.ag_graph g

JOIN pg_catalog.pg_namespace n ON n.oid = g.nspid

JOIN pg_catalog.pg_class c ON c.relnamespace = n.oid

WHERE g.graphname = 'xx' AND c.relname = 'xxx');

INSERT INTO pg_catalog.ag_label

(SELECT c.relname, g.oid, 8, c.oid, 'v'

FROM pg_catalog.ag_graph g

JOIN pg_catalog.pg_namespace n ON n.oid = g.nspid

JOIN pg_catalog.pg_class c ON c.relnamespace = n.oid

WHERE g.graphname = 'xxx' AND c.relname = 'xxx');

INSERT INTO pg_catalog.ag_label

(SELECT c.relname, g.oid, 9, c.oid, 'v'

FROM pg_catalog.ag_graph g

JOIN pg_catalog.pg_namespace n ON n.oid = g.nspid

JOIN pg_catalog.pg_class c ON c.relnamespace = n.oid

WHERE g.graphname = 'xxx' AND c.relname = 'xxx');

INSERT INTO pg_catalog.ag_label

(SELECT c.relname, g.oid, 10, c.oid, 'v'

Errors in restore :

agens:/tmp/all.sql:6740: ERROR:  column "oid" is of type oid but expression is of type name
LINE 2: (SELECT nspname, oid FROM pg_catalog.pg_namespace
                ^
HINT:  You will need to rewrite or cast the expression.
INSERT 0 0
agens:/tmp/all.sql:6750: ERROR:  column "oid" is of type oid but expression is of type name
LINE 2: (SELECT c.relname, g.oid, 1, c.oid, 'v'
                ^
HINT:  You will need to rewrite or cast the expression.
agens:/tmp/all.sql:6756: ERROR:  column "oid" is of type oid but expression is of type name
LINE 2: (SELECT c.relname, g.oid, 2, c.oid, 'e'
                ^
HINT:  You will need to rewrite or cast the expression.
agens:/tmp/all.sql:6762: ERROR:  column "oid" is of type oid but expression is of type name
LINE 2: (SELECT c.relname, g.oid, 3, c.oid, 'e'
                ^
HINT:  You will need to rewrite or cast the expression.
agens:/tmp/all.sql:6768: ERROR:  column "oid" is of type oid but expression is of type name
LINE 2: (SELECT c.relname, g.oid, 4, c.oid, 'e'
                ^
HINT:  You will need to rewrite or cast the expression.
agens:/tmp/all.sql:6774: ERROR:  column "oid" is of type oid but expression is of type name
LINE 2: (SELECT c.relname, g.oid, 5, c.oid, 'v'
                ^
HINT:  You will need to rewrite or cast the expression.
agens:/tmp/all.sql:6780: ERROR:  column "oid" is of type oid but expression is of type name
LINE 2: (SELECT c.relname, g.oid, 6, c.oid, 'v'
                ^
HINT:  You will need to rewrite or cast the expression.
agens:/tmp/all.sql:6786: ERROR:  column "oid" is of type oid but expression is of type name
LINE 2: (SELECT c.relname, g.oid, 7, c.oid, 'v'
                ^
HINT:  You will need to rewrite or cast the expression.
agens:/tmp/all.sql:6792: ERROR:  column "oid" is of type oid but expression is of type name
LINE 2: (SELECT c.relname, g.oid, 8, c.oid, 'v'
                ^
HINT:  You will need to rewrite or cast the expression.
agens:/tmp/all.sql:6798: ERROR:  column "oid" is of type oid but expression is of type name
LINE 2: (SELECT c.relname, g.oid, 9, c.oid, 'v'
                ^
HINT:  You will need to rewrite or cast the expression.
agens:/tmp/all.sql:6804: ERROR:  column "oid" is of type oid but expression is of type name
LINE 2: (SELECT c.relname, g.oid, 10, c.oid, 'v'
                ^
HINT:  You will need to rewrite or cast the expression.
agens:/tmp/all.sql:6810: ERROR:  column "oid" is of type oid but expression is of type name
LINE 2: (SELECT c.relname, g.oid, 11, c.oid, 'v'
                ^
HINT:  You will need to rewrite or cast the expression.
agens:/tmp/all.sql:6816: ERROR:  column "oid" is of type oid but expression is of type name
LINE 2: (SELECT c.relname, g.oid, 12, c.oid, 'v'
                ^
HINT:  You will need to rewrite or cast the expression.
agens:/tmp/all.sql:6822: ERROR:  column "oid" is of type oid but expression is of type name
FROM pg_catalog.ag_graph g

**Comment by emotionbug** [comment]
There is a bug related to pg_dump in the current released version.
this patch for fixing bug is applied, but there is no specific release date.

I would tell recommend that uses build that using patched branch.
https://github.com/bitnine-oss/agensgraph/commit/b6a1729c23aebbeb17d34043c2d496d24688d6cc
https://github.com/bitnine-oss/agensgraph/commit/8f18117f24b230cac0d928ff4da38134875ccf6e

**Comment by ns-berumalu** [comment]
Hi, 
what we can do now for our running setup to avoid the issue. where to do change. Or should i wait until next release. 

we are having production databases and need to restore and getting restore issues. Please suggest

**Comment by ns-berumalu** [comment]
Hi Alex,

Please let me know how to mitigate this issue to out current setup

**Comment by emotionbug** [comment]
@ns-berumalu

Could you tell me which version are you using?
Version?
Docker? Prebuilt binaries? Manually build with source code?

**Comment by ns-berumalu** [comment]
we have installed version 2.12 using source code

**Comment by ns-berumalu** [comment]
@emotionbug Alex Kwak

**Comment by emotionbug** [comment]
@ns-berumalu 
I have other work to do, so I will answer by until  next Monday. sorry. :(

**Comment by emotionbug** [comment]
https://github.com/bitnine-oss/agensgraph/releases/tag/v2.12.0_hotfix_1

After checking this, pg_dump previously attempted to insert Oid, so it cannot be solved without a patch.
A patch has been created for this. Upgrade to this and try again.

**Comment by ns-berumalu** [comment]
@emotionbug 
thanks for the hotfix. Already we have a setup v 2.12 with pgpool configuration. And we would like to use same directory structure for the binaries and data directories during the upgrade. Could you please share the steps how to upgrade.

**Comment by emotionbug** [comment]
Reinstall with same prefix and restart. ( It will not require any other instruction ).
```
configure ... --prefix=...
make
make install
.../pg_ctl -D ... stop
.../pg_ctl -D ... start
```

**Comment by ns-berumalu** [comment]
do you mean , overwrite the binaries. What about data if we have .

**Comment by emotionbug** [comment]
@ns-berumalu yes

**Comment by ns-berumalu** [comment]
@emotionbug ,

we have 2 statndbys for primary. Do we need to recreate them or overwirete directly

**Comment by emotionbug** [comment]
@ns-berumalu I think you can choose in the direction you want. Anyway needed.

**Comment by ns-berumalu** [comment]
Hi @emotionbug , with this bug fix binaries , we are trying to install pgpool on top of this agensgraph software and we are getting below error. Could you please let us know fix for it. we are using below command 

/configure --prefix=/etc/pgpool --with-pgsql=/etc/agensgraph/bin --with-pgsql-includedir=/etc/agensgraph/include  --with-pgsql-libdir=/etc/agensgraph/lib

errors

    googlecompute.sre-agensgraph-ubuntu: configure: error: libpq is not installed or libpq is old
    googlecompute.sre-agensgraph-ubuntu: make: *** No targets specified and no makefile found.  Stop.
    googlecompute.sre-agensgraph-ubuntu: make: *** No rule to make target 'install'.  Stop.
    googlecompute.sre-agensgraph-ubuntu: make: pg_config: Command not found
    googlecompute.sre-agensgraph-ubuntu: make: *** No targets.  Stop.
    googlecompute.sre-agensgraph-ubuntu: make: pg_config: Command not found
    googlecompute.sre-agensgraph-ubuntu: make: *** No rule to make target 'install'.  Stop.
==> googlecompute.sre-agensgraph-ubuntu: Provisioning step had errors: Running the cleanup provisioner, if present...
