### ISSUE TITLE
pg_dumpall backup is failing if db name is contain a special char "-"

### ISSUE THREAD

**Issue by ns-berumalu** [bitnine-oss/agensgraph#588]
we have databases which are names with xxx-prod, xxx-dev. Backups are failing due to db name has a char -

its taking backup which dont have -

below is the err, please suggest way to take pg_dumpall backup

pg_dump: reading publications
pg_dump: reading publication membership
pg_dump: reading subscriptions
pg_dump: reading large objects
pg_dump: reading dependency data
pg_dump: saving encoding = UTF8
pg_dump: saving standard_conforming_strings = on
pg_dump: saving search_path = 
pg_dump: saving database definition
pg_dump: error: query failed: ERROR:  syntax error at or near "xxx"
LINE 1: ...CT oid FROM pg_database WHERE datname = ' dbname='xxx-intg''...
                                                             ^
pg_dump: error: query was: SELECT setconfig[1] FROM pg_db_role_setting WHERE setrole = 0 AND setdatabase = (SELECT oid FROM pg_database WHERE datname = ' dbname='xxx-intg'');
pg_dumpall: error: pg_dump failed on database "xxx-intg", exiting

**Comment by emotionbug** [comment]
Duplicate with #587. Thanks for reporting.
