### ISSUE TITLE
grants issue while restoring pg_dumpall backup

### ISSUE THREAD

**Issue by ns-berumalu** [bitnine-oss/agensgraph#593]
Hi ,
we are using pg_dumpall backups to restore. but we are frequently getting below grant issue when we are restoring.

agens:allbackup.sql:511129: ERROR:  syntax error at or near "spm"
LINE 1: GRANT USAGE ON GRAPH xxx TO readwrite;
                             ^
agens:allbackup.sql:511130: ERROR:  syntax error at or near "spm"
LINE 1: GRANT USAGE ON GRAPH xxx TO readonly;

when we are running with modified one "GRANT USAGE ON SCHEMA xxx TO readwrite" , its working. Could you please suggest.
=# GRANT USAGE ON schema xxx TO readwrite;
GRANT
=# GRANT USAGE ON schema xxx TO readonly;
GRANT

**Comment by emotionbug** [comment]
Opps. We missed that.
We'll fix it. thanks for your reporting.

**Comment by ns-berumalu** [comment]
@emotionbug 

Is it bug, how to fix it in our environment.

**Comment by ns-berumalu** [comment]
@emotionbug 

Any update on this. Any fixed release for this issue

**Comment by emotionbug** [comment]
This has been resolved.
The patch has been applied to the all branches.
It will be available in the next release.

**Comment by ns-berumalu** [comment]
@emotionbug 

when next release will be available. Can we use this repo to fix the issue on our current environments

**Comment by emotionbug** [comment]
release date is not considered, yet.
also, if you want apply patch right now, you can download and build from specific branch.

e.g., [v2.12.0_hotfix_dump_restore](https://github.com/bitnine-oss/agensgraph/tree/v2.12.0_hotfix_dump_restore)
