### ISSUE TITLE
Quick question:How to use agensgraph

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [bitnine-oss/agensgraph#596]
Is this project like a full fork of postgres so I in order to use it must build it from source.
or is it just a plugin?

**Comment by RESDXChgfore9hing** [comment]
or is there a way we can apply as a patch?

**Comment by yjy44** [comment]
To use AgensGraph, fork this repository and make, or download release binary.

**Comment by RESDXChgfore9hing** [comment]
i tried installing with the installer binary.but it seems to have error.
![snap](https://user-images.githubusercontent.com/75789716/206168166-bf3b39ec-7ead-474b-b010-a85103793e70.PNG)

**Comment by yjy44** [comment]
I have to see all steps install progress. If you okay, could you show screenshots per install steps, and os you using?

**Comment by yjy44** [comment]
There are no further details, so this issue is closed.
Please reopen if there are additional details.
