### ISSUE TITLE
2.13.0 and 2.13.1 make install errors on Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by bioxakep** [bitnine-oss/agensgraph#608]
make[6]: Nothing to be done for 'all'.
Please, test this and report reasons.

**Comment by seo-kw** [comment]
Hello there. My system is same as you mentioned above. 

`lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

But I just did which is written in readme.md

I think that build process didn't not fully successed.

How'bout check readme again? or just try copy & paste this!

```
mkdir temp && \
cd temp && \
git clone https://github.com/bitnine-oss/agensgraph.git && \ 
sudo apt-get install build-essential libreadline-dev zlib1g-dev flex bison && \
cd agensgraph && \
./configure --prefix="$(pwd)" && \
make -j 16 && \
make -j 16 install
```

(All of things are in temp directory and you can change destination wherever you want to.)

I hope that your problem have solved...

**Comment by bioxakep** [comment]
"git clone https://github.com/bitnine-oss/agensgraph.git" getting 2.12.x version instead 2.13

**Comment by bioxakep** [comment]
Ok, solved. But now pg_trgm.control is missing...
