### ISSUE TITLE
"make install" failed on Ubuntu 22.04.4 LTS

### ISSUE THREAD

**Issue by duerwuyi** [bitnine-oss/agensgraph#652]
$ lsb_release -a
LSB Version:    core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

when make install, I got the following error information:

make -C parser gram.h
make[2]: Entering directory '/home/zhouzhou/agensgraph-2.13/src/backend/parser'
'/usr/bin/perl' /home/zhouzhou/agensgraph-2.13/./../temp/agensgraph-2.13/src/backend/parser/check_keywords.pl /home/zhouzhou/agensgraph-2.13/./../temp/agensgraph-2.13/src/backend/parser/gram.y /home/zhouzhou/agensgraph-2.13/./../temp/agensgraph-2.13/src/include/parser/kwlist.h
/usr/bin/bison -Wno-deprecated  -d -o gram.c /home/zhouzhou/agensgraph-2.13/./../temp/agensgraph-2.13/src/backend/parser/gram.y
/usr/bin/m4: unrecognized option '--gnu'
Try `/usr/bin/m4 --help' for more information.
make[2]: *** [../../../src/Makefile.global:769: gram.c] Broken pipe
make[2]: Leaving directory '/home/zhouzhou/agensgraph-2.13/src/backend/parser'
make[1]: *** [Makefile:137: parser/gram.h] Error 2
make[1]: Leaving directory '/home/zhouzhou/agensgraph-2.13/src/backend'
make: *** [src/Makefile.global:388: submake-generated-headers] Error 2

I'm sure I had installed m4 and bison.

**Comment by uhayat** [comment]
Can you share the version of autoconf you are using ?

**Comment by duerwuyi** [comment]
autoconf (GNU Autoconf) 2.71

I had installed successfully by docker instead. Thanks.
